In [31]:
import pandas as pd
import numpy as np
import requests
from sklearn.neighbors import BallTree
from functions import trinoFetch, write, read,append, prodFetch
import warnings
warnings.filterwarnings("ignore")

In [8]:
iotList=['246F4B3F82B5A214','80D52CC004987C7A','20327703C839920D','F24AC2D9605F6025','F24AC2D9605F6025','8F7FD09AC0556907','7BC0CBB189F657EF','3668753B4EA6F312','B90DA0FB998A7331','A2A06BEDAE222E89','84EC17290FDE2F03','0492D8591F7EB91D','AE08E31B60FB6377','726D643AEE7FFE99','0EBF75859A6A26AA','0EBF75859A6A26AA','99752C280979FAAC','588EB341B382E6D9','EBC1EC9383D43113','3F713D433732E1AD','77E105A0A996E388','6F71929C35439616','9EE24B7C901A79FE','08B2ECC1AB2D46DF','0C7823E957BF9A41','30BCD841E97B9518','0C7441CA8EC7AEAD','A3600941AEAE2457','3189773EF2535F22','452FA0C33A86F425','54636480BDB1AF03','284EB082D30E9BF6','794E20F0CA332665','15129E48106F514F','C7F19DB0CF343CEA','03B4E18DECC685F8','DDB354347C76B872','E7CD2C6B7E25DC50','0A1CBCFEDB2C9B98','0A1CBCFEDB2C9B98','869137064985013','D972C16995811566','5E93F1F88A1D8462','863674079800130','721C4606F8815F57','869630057418034','869630057460606','869137062509476','869137069258481','863674075749489','869630057446167','863674079786495','869630057426342','863674079420251','869137063567093','869630058728837','869630058895503','869137069261055','863674079791982','52E7919C134BD4AA','869630057435624','25967B5C4376BC04','58D2AFB406EC1F7B','3B532FE8DAC74F05','A3EB944E2FB9C3E8','B35CE3DDC7114DBA','869137069121069','869137069120608','869137069149961','869137069167518','DBCDD597782352E7','340D10DF6DB4B4F8','D71CFCB05D5EFA44','F82A995475613C52','2384486E9458B7F5','2384486E9458B7F5','65F5C2DDE88987E4','60D18F71F4A5A1D9','73CC1AD54F864A33','2F4C5F4F61971623','4780C756934AA445','57E11F2D585D264E','640C17BAD71A0594','869137069141992','3ECEDBE0A35AB2EC','869137064921323','29172D645098B964','F59A9D1350642521','71E9E5301BCCB31A','9830E0338030F725','DAA50E8F3320354C','4EE632AAD9C49FB6','24CC9CB9C9F2D18A','FE1D4B60492570EA','BF118405CB2ABED0','DB0B712BB5237FDB','E41C6757720F9D1D','550D5CACF3B0DE94','4D28DAFA48E05C8D','4537BB5A04BCC9AF','C8628FED053154CE','44D2A7EDD44FFC1E','A80CE4A9893FCAB4','E75460260CAD6589','E75460260CAD6589','A8AE1E07B63C20F1','559205D12BCF636B','4784A649FDFE9CB7','52A3759763839A37','6E2689413417F38F','C68552DDD36E7085','869630059414031','0EB2797F7163945E','0EB2797F7163945E','863674079801682','17A19C590563E8F0','F83E4F9FBBB7EBDA','F83E4F9FBBB7EBDA','931633A0F3055936','B325D9C1D6CE1367','7A963840B0A7D3DF','BA645B6A820570BD','5422369E5F9786EC','09FB1FE7A89233CB','DECFCFF1CB34C362','863674079419345','37F22F99B4C843CF','1FCD02F793F71399','9C8553EF26A50B5A','79FE8BF21535F6D4','AEEBB6152B299BE8','991FCE342FEC26BD','047480ABEB9A3292','869137069149342','869137069149342','869137069149342','D56DE10C541561D2','55BCD8DDEB52F43A','277DF4BE07549BF9','B430DFD611CCFE50','83E69F0B5EB785E4','B6D52F47C6D7851D','04D02F9C9039691E','86E731C290D3A9F6','BD8F7476EE6BF62E','FB790B67A4BC9B4B','ACBB131CD6F08006','5E9A4AB7C9E02B6B','416D777598E8C1C8','4CE821C1B71EDC34','438B4033209372B6','B7829CE7BDC594C2','869630057409975','C907BF4C33186209','E559D58E35901A5B','865619DE031956E6','F450AC5A6B28F4C3','90EE1E12B9374322','124DE74461413F2F','9980459434DE072B','869137063444772','8DCACD274EC317E9','9DCBAE03E21E9D82','B31CFBB256880B26','E2E7DD153A7B93D6','01998D5F38165BF4','485A6D8ED0DBB53A','DAF901B3BAF1D639','01E8E24717C8C8E5','31707FF35F6CB97F','0C4651DE9BF5B38F','259D3B5D68E381E7','44AD3DA04A288DBF','2CCD3D323494FBEB','3576BCA05234C2E8','CE4757182E6C251D','BE03A670EDF99DFB','7C4894B6DE7A569F','F3D24B7B67524306','9534863622DA10E1','869137069201457','5F1E6CED62801D72','7D66E333EE77CC72','2777A320DF738097','09ABB2BD66D13BA7','B1572F5315124E71','0ECA90C47F38C660','E17E1F298A2628DD','E17E1F298A2628DD','B57C81F94AEB7977','6FD59759B4A28C80','E5529A9C0B622ECC','869137062679147','4E62422A528F9C9A','0743E46084C5D93F','04EEAE4209F38B54','63C4F6DBED056E34','585B56425A717A45','869137069246221','37C1A7A10D734576','271D44633C0A082D','5B470F573BC02ECD','D5E6F1681DC39478','D945D2A47A987FDF','3E0EE9F4BEC96A29','78A625A3A6D80BB9','8ED88771FA8E7FD3','A4CC6D6328706056','67D439177C9D5374','6C24BF33D50191C2','92F90C61E64E674B','098125251157A44D','DB753CAD18C62FBB','9D3CC52D05F1FD31','01656DF776BF5B7C','942F592FDFF6313D','CA60C3F64C4F5CE0','29E3FB0DE0DC7170','5ECF3FB34EF5C3DB','5ECF3FB34EF5C3DB','A27320F5F468B19A','1D44BACBBA862CB6','91E403C9D2AE4D36','3EB9B8D71F9C1E58','CF4873C436B1F021','D3816B8B26D6F314','553B6123941A874E','084FD857EFA851F9','70F45E8C67C464CC','3F03B289F1CB5826','54F3C2745234442A','6CB923AB9BBF1990','B77570570809BA01','812D5F594C2BAAF4','0DD69CB24F4BF5AC','0DD69CB24F4BF5AC','45D61FC971820FB3','73D42BA09FCD8615','EF8FFCC8D7FA1A11','7CB5A20C59E22CA1','0BFE49095B698BD6','619B8734E0E162E3','B68779A51B29DC18','1A4A4698D38062F2','A7AE35C7AD5B6B1D','B250BB65A9C8B35E','4ECCE30EF6080D22','19C10F463697F5F1','BAF8D509DF03BDA9','8407605B7E20C5C2','2654BB5A0A0A50BA','C2A42856E89C9B8B','4BB1E273AA6C5447','61304AD051944D84','C88ED4DEBF226630','795CC02290C7B43C','FBE9CFB15A050419','AC5C919DAC56E4CF','FB8CE030E43A65F3','A1452C5B697DA3DD','3D5B37D239B1DEFE','87537BF460BC173F','1D6A6168DE9AFE18','C9A2CBCBA1CCD2F8','7B9A034EA2E021C8','329D6CC291EC4454','65B43A3524676D98','6F4B59FC200B76BB','28D7239AE4CB969A','299EC58DFB1FD320','1A362E07EC287F3A','E3ABE0BDD6B44D51','AFCE09D75B4FD5E9','AFCE09D75B4FD5E9','D77D563EB4FC29FD','3E6C0D36385B7623','E6159D73D8340A9B','39A99704601D463F','47D269FC73994B47','E296FBD0C8C99F21','AAEB46B279A22942','EEFBDD6F713A0A85','AD12BAB5423CC0B3','2B5191F515D36F37','993A24BA1F0AC169','C2D0CB032148E6BB','537C3C43DF3FBAE9','DB556BB964913391','DB556BB964913391','B5B8E3819AB30558','996EDF13BFB6B9D8','71901F995ACED42A','C8E7817946674A49','6422E63254CE42B8','4EE3706D46299E1B','25DDE5A75B74C3FB','AF2C61C5EB256311','DA6FEA7174806B62','1758D3A5045531C7','0354BB310CFC0BCB','5D532ABF7A9E6F03','5D532ABF7A9E6F03','715A971C38322F17','112DA35B49788A9B','75DC9A442DE4AB20','675A7C53C848C6B6','7BBE57073CAD81A6','56B46EB0077BE140','A5D72ED83B0D904D','284AD51DE3F22B87','166286689AD105E3','03E96F880F6DC7A4','E717031455627C61','4C2F67BC1D9786C3','8058F76EADFCEB0A','543DC93E23D53846','21BC5E69C928C235','54FA7B2050397705','6773142CB62D161F','A311CF1BE7619607','AC26BE05C8E43913','C0826C14FE17D561','A574FD3B5BF67CCF','71D87D153E984496','D1DE534435C5F101','D15843BB4E587177','DCFB9CC295010928','E9A9864B0F4E08A8','AF358D58FD5D1BEC','1BBAF35A548E3F1F','4C60E826B4DA7CC9','1BFA2F1CFC56F1CD','0A7133DB7BCDE3D1','11DD265A493950D7','7227CAED8C2399AB','869137064929060','B55FB798975D85A8','B55FB798975D85A8','47F18AB85E55D1F9','47F18AB85E55D1F9','61AEEF1E9582DF46','D4B7442ECEEEE675','869630057397402','0B141B2951A9DB3B','D2CF6AB2A2177A3F','CAAAC6246C87EC53','0D7C665639C1AE4D','C52242919E836F91','A5B308378B0838F3','24F94BED53696846','39C962AA94D5A8EF','8F72689A8709275A','2974BA910567E10E','626AA4993D4E5A0A','019453E983B8876F','6DE42749921A302C','80D309B4D452544A','09558D1E9D71A22F','E75BE5D6D31C8257','EED27DFB0620D3A6','2FBB51369FA559D7','8BDDA429D30551C6','E037B0911A3ED4A3','B47DEAA375D287D9','E38C31ECDE44429D','3B70714A465B576F','0BE791F46D1ED1EF','928A58FC0364CB3B','7D09EECE596D76AE','56851E9EBA6D7FE2','ED861D908C8B2A36','83EA362DA0BF24C3','B15C76EFA99E68CB','CCB328B70701715D','3F281CCBE5EDD92B','919ED3D3C8F13A94','863674079330740','A5112209D4D44499','0EAF57D44475F884','869137069168144','4564BDF55F759226','155FE7668425826E','869630057394136','7328AB748D6CE085','DC128A26017025F5','C3D89E12B9E1253C','8E1D178FC4966D57','F58889A010BBD5B9','5CC1C1EB6C949799','3003DADBE73D8560','10CAE9168D0AADA0','5E0B87160C3E8093','E53E666FDEF997C0','69F191778F1026D5','BF2CD16DD6D70862','C6028A84A25F82B1','25F63C6378790687','D17CBE6D0AEF63E1','ADA7F430B9DFF273','0134586E352BE3F2','CB210A9C1ED9AE43','7D048BFAD67044EA','6D74FBD95FBC6C6D','51DA19F941FBBEC7','A9D093A2B9F521A7','D8B1170299CE0984','9D7AA42C25B577AA','E9F537A0A6DAFCF3','1862BF211D4BB91D','042244F406B64EF6','A53E2140F11401ED','77B1B9E8AA0BC8F1','EA97EF927B81A2CB','56F3E23AFCAA4AF7','2D03E8416B4E1A0E','589D2296B4B45661','112A89A3AA479994','269A558D1BB0BFD8','2093C6EE29A8CB30','03031B7CA8B2E1D1','A7224A5237B8A056','A8E4B8A48844A842','6EFC0C87C318B2A2','78C20616965CFA1B','E2A023A50C1B2614','4CCFEF084DC8A369','CADF8DC43BFB6E33','5701A8286708E811','A2888EC2C35E3AD0','0C43C44218BD375E','F0E8AB2842782757','15E9B81BC96CF741','A0FC3C6B1A7B8FAC','7A073E2D734454A0','0F4A721A86D081E0','E9B6CD0BF0DFF011','307BA5F52B7CDA9F','FBBE4768818EAA0B','0859107D87BDC9C9','1F66FC318BDA49BC','68E59E3A8E57ABD2','68E59E3A8E57ABD2','FA883B360B194583','416D4123DEC0D30C','BF7F79BEBDDCB7E4','8632D64B925E4F5E','869137061556239','C20CF63303ADF344','CF714BD676222629','7F6AC83741C96A2C','CD08313E4ED9251A','6EFA63BF4F189E7D','FEFAE2961B5623FB','1B2E95B20D4CC62F','414A8D622D7BE55A','B1B92EE503E6C5C6','CA56C6E256E4B962','146220F810F4F31A','BB729C4F29A3EFAF','E384BB8382E3F5EE','138091B647AB7945','12C38509D639B1AF','D8670B2CB222DC4A','266B134BE59530BF','1829E0DDF0BFDB93','0952274662D9C94A','309CF1F4BB774409','8E9A60691115D90C','0D59689B4D99100D','1F8B7BDABD4A7AC6','B6913E6564ECCB24','BF4AE018CE5B663E','BF4AE018CE5B663E','BF4AE018CE5B663E','FA9DA5845EDDE985','6C6A958AC1318555','841ACB3016BB206E','51CFCAE209BFCA37','88A2CE9BF4A8C8AE','6AE6FE66E2C5C094','531227453F318F6C','680907368B1F3C98','B39CE46053439161','DF8383405984CDD3','FD9D8AE4CA09E9F0','B15417667FB339D8','448B3306433475E2','E5B37DB529E28B0C','869630058687835','BC6A16F711FB56D5','58294377D79594B1','2F3942DB323B531B','EC8E0C9ED2F82050','5B9F72A9A142F6DE','3E2BFEABBB8BE5E3','5B77B943CAA5E2A5','5B77B943CAA5E2A5','034B615CB3FA80C3','45AD28C03A372A61','2B4A8BE62FE24439','920497D7B253AB63','4D10433A0896D8B3','08FC24FC5BE78164','3345ADB76C1635CD','390B49208A1CFD4A','CBDFA5E4F391ED1E','D2B3D7C833CD9B41','29475A9C4474928C','753E17019A70847A','1E0FE2F6B02E25F2','488CCD9C45AAEA1D','70B808B3CFFD1528','D7E82481266E237A','21432FF207A66196','2770AA9BDBD2DEE8','F6C48A36662C4933','0B9C592A5E0EEB23','0B9C592A5E0EEB23','39E67E9B21E9054E','A0A5566E229284DD','126B3FF234880E77','29E6684ED8AB73B1','905E98858C65799D','8317B2A29012517B','7237A6D3C144ACF2','7237A6D3C144ACF2','294EF32D510E403B','A573127A56DC832C','38F8995FDF5C82E2','11D052E7DEBD57F6','4DCB87E6406F14AD','92B446CE93FE3330','488767401C51615D','90E86771E443313B','BFB59439E43219B6','9C534D9AE11AAD73','8FC9EF3DB3E0E679','111764D053431E0C','DE96780AB8577EAC','92BABB9FEF96C039','49FE2E6FB10B7E7B','23B6607FDFF4BB0F','71BA90AB7E5B1DCC','82EBA6E054CECE19','E03389B5513AA475','FCCFE49ABC1725CF','82F8264599F1CAA2','83A7B50CD7F915D8','DFC72458C473B2B7','DFC72458C473B2B7','424D80E2864A3C02','258F246CEF2B2BC4','9D254D542E4727DF','2850A50AEB126BCF','2850A50AEB126BCF','F8705B8572880F34','375721BF6FCC6176','9F39A2403EDC9D60','576C109176E60778','E1639F7BBA0C0ACD','864710056656597','6922A8B7D32B4D2C','65A1BD573BDCDA2E','65A1BD573BDCDA2E','01555517412C24BB','ECC64B590DA8CD1D','A40C080E58274C3E','86C3BAC10582BE43','6AF06789B7DC236B','0CB66993C818BA21','0CB66993C818BA21','DFAAAE6AAC5AD499','A817E1F2D68940BA','52BD463FD81D3F08','56595BCE62B3BBAC','14F3751FD4FAB334','869630058777560','209E28EE5A438207','869630057591442','869137064953771','5E76F14C2F6120EC','09F31C36FC021E4D','869137063607956','A83D566196DED41B','A66D7C86AC159939','E46AEF21673B9F29','03DB9AF88A4CA3AA','3E6DBE98752D78CE','AC77ECB599E134F4','FDD89A37A3275C93','85C058364C1F69C3','3E828250ACBA4864','F41B5ED3E2B83B18','1EB8C76F14552143','40E56109198E9A55','CE875174FBEB85C2','869137062602032','2FA877C8603013D8','03DE8DDE6C929BC0','8615D83D68C5B3EB','9124ACB59D796F09','04C35E22578CD46C','3AC90889E04330B1','897BAA31BE696AC2','01F4BA65BA0B486A','702D64B956A12E96','129DEC1C40167890','235A80CF1013C335','A73B791CD0FB765D','D5D9617EDC9F7BCE','95E786872126D1BB','4E274B72FAB9D6D1','8B8AA842BCCBF29B','BFE13657B666B3FE','F9C0452C940FAAC8','541A56B4FA9CF14D','D7FBF111FABAEA09','659F54C724028E46','5E3510F528450772','59672CC31150E656','5DCC4FCE312995AA','863674072247602','863674072247602','863674072216250','863674079771588','863674072263005','863674072258500','8D45C9AC3548BDDC','2024CAEAE415C416','CD7EBF272AEDE5E0','72F19D0E73659CA5','2BE699AF40D93DA4','869137063590277','4A4C8F97CE5FAD86','B27E2EEF4BB1B10E','5AE29849A9A93F42','16EED4DA03569AA0','63BCA929FE8A10A3','AE0BD26643CB093D','BF5AAB465095BF1B','EB0B1C9308B35B37','3E69275C68956EDB','2518D6326AA31F08','D8B7A20D16812264','112C14767805D638','7996074E181BB8D9','2998F48B7472C85E','23BA0C0AB3E6B58E','0C5B3CF6BA1F1927','B8FD32B24BA0B9CF','9E55F6E69788B9FD','EB1552BEF899A688','BE242A1063352B5E','0A4CEF8A828DED8F','4C6A7BF28BBD1342','B59ABE2B94A55541','B59ABE2B94A55541','0CB13D91EE4CA75A','1A7F370BA50B304E','CE1E5A219A4D3F70','CFE9E0CCC78D0816','CC5930DA2C3CC019','F45E25AC894A62BB','2437573433A54F86','A68AA221678628FD','E1F6B3D8EE4ADA42','13EC2BA0683BD626','F67BABB2DEAA7881','08B2ECC1AB2D46DF','0F3436E1F55D7056','89BE1B1B571DD852','EDB4D355A823567B','5BB4592126FC4E70','BF75E4FC41096EBF','8AFA99851E4A23DB','47E32C629CAD3DE5','6BC6FDE57C1FCB4F','1E678E4DB5B1DBA9','140B32F157893E50','CABB2433CC838323','38BC3F037D6A624D','2ABE4EA5965A7171','C1C3619C8D5EB7A6','715CEE29CEDF390A','3ECF39D9FA852D40','6F52072931BCCE07','6F52072931BCCE07','EEF3A25243911658','7D722F15A479C43A','39F6249B1C768D14','5805B50ECB1FFED4','2DD585D8EFA33B73','2FC064E628B8E205','A58362C9664A0F5E','B7E5F0C54503EB12','FA31A0B789794A40','42937CC06E95A88E','42937CC06E95A88E','502CAC37F1201E6F','6D4AC4990AAFB927','F9495FBCD815395B','7ABA1B77A8CAFA78','5D01E26566B862D8','B84A5D7775B6B7C1','869630054368539','7433979E20E5AC5A','67F980F53D217E2F','1DF327EC752F6823','3EEE1A2136E011E0','13DB67C0B56F5CCD','869137064973480','1D6E61A9E3E71C26','23BD187AA45BE8CB','C9CD5BDBB5F13722','E1E16A411A5AF46F','863674079781074','4A5EB3D42114A067','74688E90B3CEE770','FDEA325EDC75CD74','3BD610DDFE71E9EF','82512534963F1622','32A86D747A33907F','59894B7FA7AE9403','51F02D3218C69C38','E3B70ED74C27A83F','D3489592482F5EDC','E56D9E2FFB98E867','1F070ECFC60FE338','B58BBF8E995DAD11','DA0EABF8B9440CCD','B54B64055BCE45B9','7614DC1E56A71171','7614DC1E56A71171','BC65584C2E8CC71F','2B4B58DCDF2CC778','D1CEF9524926B751','1CF9A44A128341B9','09533C4F913C35BB','62A3F5D8636F335C','1F5F7245398DC51E','A5300B52C4936713','8F42C18748F6A2B9','242BDE158B024254','77A30DE3F65C4C45','0A9BDF0F7FD64F84','7BFDF0B30E44CD9F','D50248D2CEC8C481','FC4EEAC2A046ADC3','5B7A337FD192726F','6846BFC178A47018','87030A53D09C99C3','BB239D50D1FE1016','4B21C4925C86F01D','61820F9EEBAC31E6','4345071BDBF6E0C9','71C97219BD2C7DEF','07703E5425918BFE','D4559A01AF30ED58','43252FD648618173','43252FD648618173','43252FD648618173','116ED3EEE93CB7A1','23DE7CEDE8539FA8','D5DA6BD0463DD4FD','96D0BF7202F08070','847327322FA368B1','A7EA84CD087F54BE','0A94A98DD8BF0AA8','0912983F26A433A5','4E3268FC0A8437D7','19D13911B6BF3F3C','910D4DD4608ACE41','A2C952BF81D689DD','A2C952BF81D689DD','8F65E9DAA325C55C','7EDFDBC3808CCC4C','06338C6E44A55D4D','BFD6CF6EE5B8D1C0','D0C188203482C572','D0C188203482C572','C0C8CEF591CEDDAC','C0C8CEF591CEDDAC','8C661A445295AF9A','863674079408017','BC83F00E881BDFB0','55B5974DCA2DE5B6','BD99CDAC52EE6D16','624CEF0AEC9E8BDA','869630059280580','CC0D8A8AE3E43180','509B97FAB1BEE5D8','869630057605218','7CD14395C98E595D','3FD652FAB27AA973','E9EFE97B99B77EFA','A0274E706337B222','A0274E706337B222','FDED7A84EE656BBA','E798CBEEC406704F','52CA2F2C9799C0E3','20CA27DA489A1BCF','3C011E64AEF1519F','79C5CBA1739D621A','11249609B925686A','869137069188589','869137069188589','869137069188589','2D6F49D1DB685F0A','2E7955B271D13090','C3C7ABD27B323536','C17E54E2270A7BE2','C0CBEFD4407B4EBA','FA032358D8028626','F37FF3678850BF70','869630057459202','56FA374A1BB9EA6F','B5015A07E40CE0A8','F1E8C11CBA569185','5DC2ECA0898A4FC7','5F9E95BC41C24942','864710056647810','C35F8FC4786B6868','0AACE7273C0E14D0','B08FBF197898EB9B','918A9C0606223CB6','C2D2761567C21881','BBC339E5DCCDCFCA','E033105381852FDA','8078A8C316CD5E6F','05B6C22E82692BB2','C287BFDFE6E29F74','282CA271B2605916','B20BA0B70BFB7B3E','FA15D986A45597DF','C248690BD869327A','AC318FEADEDFAD4E','70C53587C4818E43','3707433A8BC0DE65','F29A248021A1FB38','82A6BE0AEC6EE6A4','063459B34EEF0C62','F9BF996FA80F2D13','4F557EB66C9CFEFE','9CDA99BA1279ACE7','6AB1A6968099F92E','13176AC0D155EBA4','40372B7CCEAA8122','91519E1DA2727635','869630053745752','3A686ECC9C986FBD','99752C280979FAAC','743E070CD06DF8E3','CD7DA579E2A43CE2','D8F54187A7467D92','907372334126EDB0','7832211EFD701DF2','D45C8BBF5B8702BC','50F9ACDF402DE954','869137069221166','869137069230209','CF39D66ADCB41EA2','035CD91FF231113B','864710056643975','869137061477824','283E851A72315804','FDD590A6334B220D','5B86D38D9053C05D','B7351D3C4344FDB6','04DD49F892789624','04DD49F892789624','F6354BD6842A2C92','4580F4374A94D5E2','4580F4374A94D5E2','F8CE4DDF23425126','7E147B9C51D93E2B','DA275A0F5994FBAA','E3098F69F679845B','C2F9387BECDF8988','869137064950561','869630057391637','869630058645767','869630057568150','0495E93D54ACF6CE','87A27ECD54A615DE','64EA337029A1FAF9','E6A35B54F3F73DC8','869630058895404','869137062507959','9D3FE2F1B3833C2B','A5311E5EF4E828D8','DD15DB2A094B16A1','E026E2A7D24BAAA1','1086B0E5DA6035FC','B4DB28C463DE3307','CBBD0F99DD5BCC2C','863674079420509','863674072274663','863674079771166','863674079803290','863674072216359','59109856B54E9552','274610285BA95206','8C56314CE873BF98','EC3350ADC2AEC1D3','028EBC53D05F5498','2E8710850581FCB3','0D75F43C39DADC21','AA16DF398CA8F75D','960604411F01173E','BE70E9D4BBC60280','F37A3C6B09667A66','2A678DA2C0AAF04C','481AC6F6AC866209','583FB75DB90A0674','DFCF899E396E06B1','E50DB1BD13723098','5AE906A28015E767','5AE906A28015E767','E2A5510ACD2A861F','355A61629F8833E4','7A1B474493389FFC','8C3747C04AF8C536','062C30E275542D02','148D2C497E993809','87F780D63A9B4B5D','997934DF9321DD33','58E4F9390447B520','DD7FD1DB2D593942','D2C0AF61312D38DE','969136E3DCA15A6E','B958BC21C1E3CBAE','5172E984B5DF0895','7D073ADC7A622B0A','222F9BD828C12F61','222F9BD828C12F61','DD44B2303D8F2729','3112DBF4790570FE','AD3BAF878205094E','445C67D54BDBC671','1ABDDFB5CD0171E7','3B69350DC971D76E','334BBC079AAA9D87','A28A9B53ABD3BA77','64490D573D49F328','B925E717AFC22FF0','21661AAC83212662','D5131C5B9A043655','E8775156AE0E8D36','B7DAB1E85EB507B9','1C68ADE11F5D68A1','121B0659E3253DEF','25FB083716E68741','25FB083716E68741','355AEEF47622CA46','19C7B26C9F34A9EF','D1BF025579CECC5E','B9170A9CBE44AE5A','82AAC0DC640788D5','30AA5F75312EF27E','E358E65DED0AB00B','E358E65DED0AB00B','44AD72594AB90C9C','6C6250B67129BBFB','05A91EFE1AF29046','39852462B72BBDA8','E3327895CEA7EAAD','863674079422489','4763AE88F399BAA4','DF12C8F9F24DC646','48EBF24AD58F6770','8FC042D7D7369024','12600850027FB590','863674079780837','863674079783567','F5AB39EFB79A7F02','863674079793236','420EBE86598E3FEF','FCD126CFD2B3BE81','F589D5B3017B775D','8615A2BDA98F0B18','4054E5E057DB6791','863674079426407','3605844AFE991F76','3605844AFE991F76','216702394CCFB9C4','FC20DFC034BFC59D','347957F13DF4132A','347957F13DF4132A','9E5AEC54417D6D0D','CD0436CE8374BAF5','38E01A6FCD5869F0','A63ED0E87C5D3611','863674079776348','CF8583DAB5A0C43A','0AEDA939C0D1BB3C','A9F6AE70EE40F6EA','4409FD8D92807CB8','869630050614605','EEF964EF07299D8B','466ED4D723DF27BD','D80A310E5FDB8A32','869630058678784','B6C987BE2C4628D9','2AD87918584669D9','DBA6D41C2A4DD278','869137062508577','863674079767263','2C78298D703B2276','869630050724180','573A1C1034E7B3B5','3B5BF755CED5288E','FD392E5EB5F2E33E','864710056638686','863674072255902','863674079795744','B2AE8DB4F6F0D464','1647D2BCE2624DBB','CCFA3282E8E9FD13','711BAB74D5823FD9','863674079763957','863674079402465','863674079396279','652990F557F37F01','863674079405708','D9C7C2DB4CB935B5','31257B70D1853F9D','6C678D2CE92A4DC3','44E93CB414B722A7','C38D3716222042FD','1603F9324DC7A8E0','71233B5BE0A3EB64','B5A25940903D83C1','869630058761861','DD55E5E10410862A','D578F9D61DCDDAAE','863674079416325','863674079416325','863674079416325','5F4C9B0482460766','2F91E22AB4731055','1488864712B0E855','E848D9C6CD01CE63','1FB99C07DDA3EA4D','869137065095499','864710056643934','869137061653598','22090C93588A9143','906D0C3DC96C1775','863674079344378','D5AFC527A1E74E2C','FB157798B398273B','605F0EDEE94D048B','312E22CBF32B953E','869137069231926','869137069226017','869137069222107','337D0B941B35CF08','869137069226033','39FA8392D7F0435C','869630057622643','94938C6CB150E524','57D2805F57A8BA14','2C42F46EC1B38934','869630057372736','04AC18CC2480693C','E9CFB748A8F5BBF2','863674079419246','863674079417265','863674079417042','F7DF8291D3FED731','07269394DD25BEEF','A910532AD1DAF61E','A910532AD1DAF61E','F5598A2A925AC380','BF751FB25CF90D3D','869137069219137','869630057374070','869137069233021','864710056667685','0270B93BDDF53628','A7D4B103B4EA402C','9049EB5B1D8D2B2B','0CBEFAC32E5642A1','59855047986356DE','8F8A9BAD1E591095','DA52618662AD81AA','94290E117A43A0F6','F547F3DC286CA25E','F547F3DC286CA25E','F547F3DC286CA25E','0A1FE1F89F90D703','29689750D180A289','8E034B86933F148F','CFC6179E3A030DCF','E0F8ABCC1BF72AE1','869137064990864','EA87E277F5850607','D2E97CBEED410378','5B922E3CB291AA99','39D7B9090EB4375D','EF04B26704C1AD50','673D2F229ED09701','6747025679474C34','F0A92C234F2A0CDF','869630058718556','B37B0B41A7562556','E209B3263684F20E','790AA45985E1F431','057062A7B82F6DB5','99FCC97A5829DFE3','118DC558D1B6EC39','C11871F79479B824','52C78CAC21F93178','BC6C73BC3AC2434E','C31A3D2237BF6B14','825A7AB143E4F85B','876D640755A2CF31','5F7E166D0D15C234','92577FF635457DE8','F4F66FFA29DF1AC6','D0067C4D96BBED14','4F9333D31C86333B','C6FC43A3EE2CA8ED','8EC6CC9981C57A51','869137069170090','CCAEF4DC90EFB5CC','869630057366340','800F529ECB5566BA','B6B528597DF1F7A1','5298D5C416DB7E5B','869630058645288','6496F54BDD8FB2D2','59F20DC82EEF6B66','839B682F3AF81C71','864710056653776','9878130AD428065B','863674079802284','47DCC0D312598824','869630057396156','46A9DA60F1012EB2','40044B127909921B','BA42385B09A63FB4','B181D7768C4C91CC','864710056638363','AE2980FC1C0CD1BE','863674072257916','869630058788781','E68539D667FE0CE6','B738B6E706F19E55','852A3B11A50E65CA','9A8B83D1AC8C6320','0AC854C424F52EB4','863674079762868','863674079779904','869137069208890','7A8C772CF3E35D6A','864710056651895','12FDAAE799F59F07','988BD4FCA2B63529','869137069254050','AFFA19AB02873F60','3825BE062E671035','DA883E578B4DB5D2','9A7EE3807E01EA20','3F4796C93A32DC27','6463143592F8FAD5','4C59226F1DEF4604','A713403B8D0F2851','2534B5CCC002BF5A','E2DACF7E86DD9FE9','7410A8C4BCE4B4C4','6CDC3FF7C4C831B0','5D7EF14EFAD86CAF','45BD8A221CA71E0E','05FC5169B4A828C3','A4CD4910E3793943','D34B217EC6ABDB5F','ADE01B19F23B460F','059A579DF0F93E93','2ADC46D14859A1A7','6852321370547C33','25E943B02C3FA56E','F4D61FE6F3EAA624','9F9D8F8AEBB29739','E46E5253DC55A962','B1CEA9F239189443','05159E03B3E6225E','D07E2C79707E912C','45DE8B7233104FE2','0275B6FEE5444F11','B817AF6AFEC46D40','B817AF6AFEC46D40','F3F08F014BD820F5','80C688DCE0EA2CBF','7FEF30ACF9423D5C','883CE67DF9360DB6','A71C660129CA6C8D','A71C660129CA6C8D','1563CF126C666123','EE40A504D89A3C3F','D741BCB327C49102','C3CE6EF4BF542C21','CEE61BA1EBC5EF83','CEE61BA1EBC5EF83','D1FEB57B89247823','6401517D23213054','B9B2B1754B67B606','221439DFD215EC20','015FE16889E008D0','4D5ED00781298DF1','5AE928327C55F2FB','4B491826E185279E','DC306DAE8F09F234','8DD2124D9065CBD9','261DA85957F7D652','FC026EDE2C43BFAA','89CCF5FA76709323','7AE19223904D5517','46C04514A5E357D7','CF155EEAAA20267E','644A95C347D896BD','E40977D126185526','9AF44F1C23674F7B','9AF44F1C23674F7B','5F8C7BAD66C8191E','E1D152F7EEFB6E4D','F3B05DC851660F32','BB17E52E57F1CD77','86BB8CB2D1D9822E','E354089FC51E571F','B366D7789A5BCFA0','11319588B3A40B02','E913BE09A312FDC9','327CCB9734C55741','9EADD893A65553DD','866C4A9EB0CC522A','03DD15D7E97A889A','B9CA1978FE306F02','3F32BEB74D2632F0','42A66D4A79A8DBFC','BEA74A301922B726','3D3D5CFC48D54BED','3D3D5CFC48D54BED','BAC4D115CB73C871','A82E4B9586390610','5C1617DEA1F79DB5','A60C570AF86C37D5','BFBB9C110E515576','BFBB9C110E515576','93AC6B6C74BAAEAF','9FE84019D674FD6C','F68CBCAD93E7E969','84092F43B2F8979F','86F25EE65CBE328B','D86BF0613F3CCDC0','1ACEDA786FFD2835','1C23224329D0BCAD','AEB857B6F09BCACC','F9D79CBB8F93D745','2E48FEFAB5E61C0C','2A9A08A6FA410D58','7C837D205D2D9BBF','8C93C0A1765351AB','4B1315CD2B12C714','863674079329536','863674079377535','9C376C84990E67B8','B6B261C57E45A447','CA0F0AA8545EBD82','1BF15F49EF19DEC0','C92F707436E9BDD6','863674079796551','863674079415186','9FE05F32A666F240','863674079402549','DE9FB6BEE79BE3D0','4C2CA27363223BFE','A068605723A21436','AC690C6EA702DF4E','863674079354658','863674079403331','6EFA3EDEDB9C192F','ECE871B77A225D4C','DF6BF11225ACF7F1','6C56667D84457DDB','4AC3FD93D04482AD','24F9CDE0700B4BE4','8B6C8AC06EBAF418','670FC4B7B67B9B06','670FC4B7B67B9B06','D9A2E6406517BBE9','D9A2E6406517BBE9','A236C85C7405FA99','4B517FC2588E0AF4','A7A1B097DDBF34EE','184357BD1DA8440A','869137069270254','9D8AF674CB164616','9785664318771AE3','FAB453E0C24EE0F3','E6EE464F87692F22','863674079443592','FA4A7DD827B07DD9','29EF065AD6FADF80','6B3E4C65B8794EC6','6922D57ED28B6C85','2EFD4DD32B2C4963','5533123CF9AB6ADF','863674075751444','863674079796247','565A75280F700AC2','7FCAC525535904B2','A5ED0D79179E27D5','FD21D76DA63AD252','869630057438206','4702934D96DD56F7','C9C708CA224702DD','A81F15A5F6C00235','0EF6793E972A3ADA','54F67939F5E7F16D','23499CF3C36DCF2A','AF2356938CFCB735','066E33109DF539D3','0D6553AD2D729B1D','869630059400071','804A66EC9C81C80E','5626745BE67842E6','869630054368976','0A7DB0B8ABCE89E9','C857F6F615E3B792','7BE90C60729557A5','74FD555A4DAA8853','10EC7190BED1F1EC','841310B30CB1903B','548E81C41F16A5C5','4AB244249B66D10D','4AB244249B66D10D','0126AB3386B2D3E8','B088C2904F72A454','35D8903722543CA2','94485B9B5C095028','B2F9D8D7916FD1D9','DA184F255F7A6560','863674079807432','863674079403463','7AEE6582528B0EAF','E00AFB3E79103950','863674079416291','273E62185D1CC1FD','944B662E6DC803EE','72F76CED3E9FC3A5','863674079428205','A37ECF13E36080B9','F9AB7DDAA219D5A3','B053DCC9EBEEE257','863674079402515','863674079394530','863674075757474','863674079445126','311F0ECDB112666B','7EB52372BBA7CD2D','37807865521ECF2C','863674079347678','863674079370506','4A29EAF088A32933','1DE9155E76C7120B','0820FD6F5FE2421A','604232EEBBC239EB','AE08E31B60FB6377','80E60A251228DFF8','3D8E317F6A8391C9','AFC4E9932890BF9A','863674072267683','67BC1C14CD7D050B','63D43F3FACE29D01','E52E841E4DE909F0','A88B2127BA805B83','BFB70A8CFA270F44','14AB1FB557983CEA','F52F7E36B84D4AF1','2D7AA4AD5CF810D9','863674072250291','E59B13C61EC55A5D','863674079416580','E736B98CC6184A7E','863674072259987','C92FF65DCAC4088E','612FDC8CCF788172','A1F1C62EDA4A7994','863674075744506','863674079796783','EF6427C675A532EA','8BA6263A2B41BC04','FB862E2942CB73BE','5D1AE6584FD9BF7A','7EECE9BF82957385','5345DA72732FC7F3','863674079411656','02F8BF0FC7EFE4DB','DBC72AF3D69102FE','863674079809875','A217CB6158986540','A217CB6158986540','863674079418594','863674075741924','237991F5A60935D0','892F6658F6EEB45E','233F8FD479ECE6EA','401491AADF20F666','FD9F065566D89D3C','37A9FB6E7F2E86AB','F837982DDA5BA2D2','739A2FB984475A51','29F0CB2B7B91618D','6F894BC624AF0606','7CD88E194DAB177F','8299F1C36A541B80','C4EF67CE33823668','9C403357343E525C','56A118321E6A9A33','5CBDECC56BFDCB3B','5CBDECC56BFDCB3B','046D95B087379C9E','738F5736516FD0A4','E485D431C2A35364','C7169679F7C2897B','36C185EF3C9471D8','B0E8B4721639C405','25DE67A38B7AB297','4ECC5BD05E0BEF90','6E30AD9FBDA7A3EB','8F69F98D6D9E6438','1A1125519BA61D79','1B5CA047311CE878','3FFEB624F13C052E','924A08B71A57DF67','55D15CE237C37920','70A12C615F93FC88','91AC34689DB21AE4','5D25695CF098B6DE','C7EDB5BE525E0391','AB4B1EE6A4B9CF38','B10278E0E6B677AC','B10278E0E6B677AC','AEA81C7747B40C32','94046A010ECF78A6','B296BEFC79889A5B','1A5A0374BDC72BC7','C9EF77DDFB0EAE0D','CDBD2A119F4217FB','C0B625D6BF34DBC0','9F84F3D40DC1403B','5D56318CB48B0748','935EC5DA289180CD','888272F7725A9028','704124E38AAE1F77','E303DDE1661B6116','9A125EBA5187E951','DB2AB7FEF3847A96','62E0FC5E66E836C2','94538E67985ADFAA','0D7D7DDCD9E637D7','CF29C5A07A15C75C','72F8D619EB6152A6','F55DC040685B57A6','AE423FC00A76FA84','6381D2ED858E7C43','99EDCF78A5BA5C95','ECC62BA7467C65B4','ECC62BA7467C65B4','E8CA91B575311CB9','EA48082C43968D1D','66C1E273273186C4','F0BADDF9607B98A3','8C10AC92732C7D37','E79E0344E7216261','6F3DA4ED9F49B16D','B0A04701CBE98A1F','AE8B3F4E8821F9AD','B4087DB8DCC7AB9F','CF16852BB9EC8C52','562B5FE36F945EF9','562B5FE36F945EF9','0AFD73A988763129','60A62DCD96580805','DF2FB2DB30984C1C','698DEABA7D92A5B9','4E83F65A92387101','1078A7DB9ED4A7F3','49BF54DA64498FBD','450B304138BACCA6','45620FBC37CC0FF7','30EE2584598491B2','386E81E6D93FEEA5','386E81E6D93FEEA5','D0E8FD565348383F','2953C2F77857B2C9','F8041555FA0F023B','F8041555FA0F023B','49FED39AE80649E6','322A0FAE161A30BD','023555A13AA542EE','EA020B11C519B444','E344723318C23390','25841BB1F81A1C5F','DA358EC6794B4016','817D96D6676F5062','DF8808BC0C89D7B8','DAB8852885908676','AE35EBE32FE37DA0','93B00D2A679A5134','586E01482AC3E8C9','AD71E1F63CC62DC3','4B5542DDDC15BBDD','C408687D19395DD6','4BF4B94D23190555','371FE5996CCD4058','2E3823E233DA0C70','CC45364AF8A2DF97','E932E80546F04665','45D6065A9AE24583','35BB745EC5FC4B5A','EFA8BDF91D1E7A12','0E2A7ED4151068C1','1C0A599DED1D3502','933CD67C27366EEB','2BB28895EC1E7B49','6E0A9D7733A6ED61','12452A2D3AD9EC56','7687A4B46829B571','331FC418E7902E2E','2D9CB0E536736518','1C97D8165850D392','25D38C9BC8CE53E2','B990CF71B5D24506','0E65B27787715E05','500B41DB4FCE7E5C','B5E25860A67BB68B','7A1E8BB4CD323ECB','04B6AF0F08AC709A','EEF243AFEAE4118C','8ED272DA5853FD53','286DA6B0FC809C40','45122A770E33B25D','9F5FAA71E8EF5439','705316751C55D60A','BA61799C8D90D040','28FEB05D525887DA','76A9DA3FCE3DAEA3','B1DDBB1552B6A56C','68448FFA012ECD91','C8694BA08EC21DB3','9653778396F43D8F','2682C8C5DD0F2997','83119D181F0336BE','83119D181F0336BE','76CBB0DF925678A1','76CBB0DF925678A1','F25AC2AFC0B4FAEE','F25AC2AFC0B4FAEE','67AE3F60759BA454','6D2AB12B07FD58E5','A1F42CD8D9F4D3DF','110C1A718EBA0720','53A120B4E7D49790','01659A2ED8C1B405','45FE89FCB230E246','BF99B8FD5BD76B49','489FD80B39B4CA92','E83F27FB8A417959','863674079317143','831C9380C58D21A5','F0EF0516D6D97F40','77EF67F99C142447','19376C6DA03E6F9D','713ED58A9C8296D2','563F5BF9432F59C1','612118BD437EF6F2','869137061106118','38C4F7FC11D00A6B','1421235992F375ED','EBB48DC935999A9F','B58DCCE68D4FC136','B58DCCE68D4FC136','DCF61E96D4BB9FE6','863674079410187','5422FE27920A18D3','863674079789051','863674079789051','863674079789051','863674079789051','863674079789051','BF2762CBAEC5B575','914C6B1F18D36BF7','6F1A91426A97A7FC','FA907DDDF5884EA6','73ECF45A692786D9','869630054306000','353F45FE3BBC214C','C2F5B62FEC0581CB','401E7D55828FB5BF','38D2271B20753331','0A5156DC096FA1E5','BF1E8F7D42A14513','E06F6CB568AD3B8D','C886109C5C995150','F63A569196D6D76C','869137069149748','42894A952885B320','590D1E16638C3954','590D1E16638C3954','1F1EA87A11195720','B62BF3C52C53E55E','067E7C553B9F4F25','F4F695C1E3873081','92BE2F3F5E418257','869137062654736','863674079387070','38F6D4713C028CBC','863674072222027','869630058775978','4A959AFBB84807A5','D7AF8D3A3427954F','FA83BD13915F44C3','11F056E8AFCFB1E8','863674079412225','863674079402184','7F72E76FE445AAD4','6C2D9154024EA6D0','F7027DA8DB04E059','F03CB4D9170C3BE3','2A0DDF96E2C7A860','B9E9A7AE5B47460B','03861C37BFACA04F','09610734E826E3C9','8714E5CD01D4A8AB','869137061462131','4A69C4DE8EE7B029','CB418CABC4C27782','C78D826FFD5858A9','AC16D3DD835B30E4','EE6C66A56CE038A8','6E13134BAC96F6C4','9B5423870E280178','1D12C64FFEFAEE54','113D3D983FA64761','BD899DD6183B710D','3A176F9B372BA1F7','83984BA96E0B714B','7437AEDC02354361','869630054409507','FB3EB578631CE1DE','C5C19D88A7B36307','37474E0AAF11DBB5','DF8CD20B30D07F67','93734AAFE628D040','22EC922EA1F56C29','749694BE214CE912','717CF616087AF1AF','911CAAED5F39B26E','BBDC1E5F1587816F','6FB85F8F18F12B12','FCD0D624C15301DC','FCD0D624C15301DC','83F14070B09F21AD','1543CF15A9483E9D','928E9A75E547D17A','657C8E1B5C5BF2E2','814482A9FBA4DFAA','74B372339CB28E7F','58071EB050EC4E47','93114717C83582F0','21F31B72E17C030C','7F109E38645DE9D3','812AC5E5D14008BE','75E0A6171D8D3913','863674079395073','5681A318A5506A42','64F8C982A78FE502','863674072239583','863674072239583','B37298A79F81592C','218D337682C5293C','F0FC7921D8528A4B','869137065112609','7EA06C163BA544BC','520BA094CC05771C','287B080B7B9F9C5E','859F465AB5F5D966','2D2150504E4F78B4','AB81AF86AA047B65','869137069203115','877FF671BEE9766D','4171DCE8B2E76DD2','863674079791370','869630059437016','1F67965CF9EF57CF','869630057371845','DED489D42891E911','869630050633910','AF8769A219EA4171','482161A6960F0450','AEA09CE38CD6E612','869630057432134','863674079795132','C334F234A88DD127','863674079427249','1B48B39965F50DC8','D67A89963AF69A5C','22AF4D7F2B04F9E0','3B152293DD6DE797','702826261E1F4428','869630050786106','BB0536B0BB1BD778','C80366A59508045E','817F290F5A4C4548','3BBA5D33E6355BC2','4055F82BC96B5B45','8EEA2DEEA5142330','863674072265893','4E6D91C6B9674FFD','5F5A17148BACFD3F','7136227D94D5BA58','0B6626119463119B','0ACD2E5B97983A99','0ACD2E5B97983A99','435D94C67BB8B8D4','10AE46EFA58D064F','4CDDC6B5811E3B90','4CDDC6B5811E3B90','4CDDC6B5811E3B90','067F563EF0B5B12B','6405AA603818A82F','65480CE2A278DA7B','869630059457931','19E01599A003738D','8BAC976DB71A3D29','73A5B21392470283','869630050599855','0CD177DD8AA295F4','9A2612494F27E6E0','673183E695AAE065','6EB772D8C90969D0','C309508F26E2FD80','865044073966956','C5C13C464C4588CD','2F9A33D3CBF9DB37','9A6F34BBDA0B2173','2D5B9D3816E5D940','057C1F8A1BE844A4','7C5FEDED981CE72C','0197223549F7F4E8','11634CA85AB322F2','11634CA85AB322F2','11634CA85AB322F2','D5526603E5E733B2','04180A900DC625C4','4BF5773623294563','85E7E4178A045FD4','3016E18433D697BD','053426DDFCF9F496','CDE5A44FAAB7E846','B229959CD5921E50','7EB2788864CE66C5','973019C482B905F2','1790FB60CCD26991','E8F37E6324E5DAB5','F7D713FB9F242320','916D45F262AF8A1A','F3309AAB111636CA','30D097C699C4E758','83CA5D8E1B8AB531','031ACCD7A0AC9AD4','468EF8C853EA56C3','F6B1C8A3737FFEE6','35481D4D59807CE7','93DD809DDCD35194','B7641CA07ADFD120','964CA06A04025793','B80239037665F42A','76CF7BFE7D6E119F','CFE448EFDAA5F2CB','9E4549B395267A50','05ECBC27297EE624','B34E024ED0B6A46A','4B25E29DB9B16205','6E320EEEA741C9C7','6E320EEEA741C9C7','B526B52140CB4288','B526B52140CB4288','A66DFD3D9E0ECC63','16BEA14979787BAF','1E759BAB469973AF','EC9001AAE4094036','EC9001AAE4094036','8E224DF78C137F39','A9EABBAD3C851560','5F374DE59657D142','66B1E8373693507C','E90BCFBA25BE1ED4','3F12BA9215C17590','A037175F346474A3','E9084EC152E5CEC9','6B253CA66E2DF19F','4FCDEE7D5B0BBB2D','4F95E80C967D9D7B','121DCC5C87A6DCCB','DC57FD01C3D15221','697650843502E16E','6B7A143803C9C77B','93830A5B2A94C6D1','096646C6BEC158F4','55BBD4B7957B4BDA','1899ADAB8BB98247','7C3E97F9B3259C22','64827FF569ADF83C','0DA1EDC9D036CFFD','EF64C11B1B84DE73','6B2392DA7C8BAABC','0868F7D863F5B56B','B951C7CCE5395DD2','74758711FB80BBD3','C7E268F9EB884AEB','330DEED5676AAB44','26B52616EDF2706C','7C3ABE935BDF5B18','2E2F44684261DA84','091A7371DB5E5813','3EF7A0477C417692','6B04BCF45452A962','C291F520D293FEE7','A3786B02D6B3A277','15C5906F26BEC5CA','7A25DAFC01D63359','90ED12A31E5439A7','77E073DA0FCCF375','28831D8698EAA7A5','3B3446290EAA90C8','1FD738DBDA88508C','1FD738DBDA88508C','D004C58D78AF39F4','AB061C8B69DB35D1','52B4CD06AEBC2FB0','0F065D495C8BA023','A2AC7BE3DBD7C075','A01DEA89A164B7B9','324E449A705E6DBF','E0A5D144CA2E7BB5','CA1AF8E61AD45BAB','9C0182BDE04301FD','5944D39778A643F6','62F3E905ACA04B71','DFDEF1E8F51340FC','2A756E82B8A6E302','DE94F85C947A1984','AA25FC2B64FB536E','BBB019B8017834E7','F160AFA6B18E7708','903679725709AA47','4703E0F1342A9453','6DCABAD13BDA4CB3','4DC72A22DB63BF05','A087CA02EAF8B302','2317269960323F37','46375BE1E6E8C3AF','46375BE1E6E8C3AF','A969573EF55688AB','B3B263832EE28D0A','8802C0D9186FBB99','D5DBFE7322ED909C','795E9FB3DBAD1572','26347F5F95DA3552','CCFAA0BBE089AFA6','3BC4668ACC99D27E','8033A824F6775C11','50AB2256F0ADB0C6','1140B898BEC853D4','B9F642C4A6C5815C','A3BD55115D5BAF93','9E27DC7488CC6009','8644DC092D43F320','8644DC092D43F320','DDAFBF9628D0D36E','93097E1F41713228','1CE859C1DD7A0975','E1F886B2441CB809','ECA9B683CADEEB99','B0DA8E292A79E63C','B0DA8E292A79E63C','C0FEB5647875B872','30522C43A6157217','AE5E334DFC577C2A','AE5E334DFC577C2A','24927BE89058EEBA','44457B363F08CD88','6CFCF075074E3C97','96BA5F1BD1671A15','78F0DA35FDC0F5C8','5BAD23DDB773C2DC','5BAD23DDB773C2DC','C64B5B186E56A45C','D0DECF2021B7B562','9690B831EAB3967F','334B1C697B6B7953','972A26A4E1309EB2','B923A625C73440B7','B48A4CA5529A6CEC','576894A48B798CF6','5D2F1BCA1032BF06','D8CBC1F13C92C220','D8CBC1F13C92C220','722080ADBCACE071','A2AA0EE7EF99C7A2','E519C9F7D863CF62','2367FD0809E352CD','97453EAE22D3EA7D','E3E1EE6D18D890B7','86DAB42A62A70166','D62760D7340319B2','506C42313B028D47','5D8255567B73F060','1AFD888FC877A7AC','8057FCFD3716CD52','688F4AE76596A472','1E176ED44C824F4F','2D602CB710D1EAB4','34D39B2CC731BF62','F3079FD6B9E20BBA','31D4A4390D52874A','9B30DB87A253BA56','6CCC566F6F55889F','84D62D767ABC566F','EFE33C91868B35DB','A2A4B20F5E7C96CE','51D0801BC5020BFD','FE35152861E8EC14','2AA00E457F964AB1','2AA00E457F964AB1','D15FE4E56610FC62','D15FE4E56610FC62','6A953AEBDC42326A','DE692F1A59269C82','CB1FDFB13D4E4C3E','2CE8532589886EBB','3ACF91EEDF6E9312','CFB84BB9C47A49EC','D1973681B802F17C','2BF812CE39BD0C9A','A7DF4092EC7C407F','677F07FA67F0E3A9','7054748C0EE341F6','16349EB05BB5CA3E','373DDC32F648111D','B0F7A1BAE3632CE9','CBFD0D958ACCD36C','642F1E982F5281F2','23483253C83EEC27','D263D0AA134DF092','ABADD9FD6E2D9A46','5BE6863D2DEA6834','A7C06C49A303C7E4','77C3C6F977B53287','23244CC019678DD8','8A0A198A40ACF438','BC652F1EC9C381B9','72940B5D64B87DBB','72940B5D64B87DBB','7CE5A219192E1C33','C663BB5533777083','499E44F0225AE3AA','CE29034284452F18','C9E737F0AD1DBEE0','5.86192E+15','5.86192E+15','5.86192E+15','349C52A0ECA83A4A','A51B0C6D47074828','0E0303B485C2ADF6','D991E3DD3DE11F5D','D991E3DD3DE11F5D','2A569ECBDCF5685C','996B4FD941291D25','0BE85382AFC46B35','1C8BCD5CBA02D3E7','2B246E323FF8C960','09F2DE490A21DD0E','BAD4C3D11592FE76','A7CC1970893CD75F','1A91A66A808DDB45','1A91A66A808DDB45','E9033EDE57EFA893','D311D2814F3576F8','63532A87FCD93C1E','E24B9626DD761D2C','0E83276DB170B8C9','0E83276DB170B8C9','7E7649B2FB13F1EC','7E7649B2FB13F1EC','C673DCA46B962E8B','174621C0110B1862','5DC60B9977D0AB9D','0FBCE5C7DE02C0C4','96CEE17E574C6857','773D1E7C628B8CE6','633F2D1F9A968B7A','633F2D1F9A968B7A','633F2D1F9A968B7A','633F2D1F9A968B7A','7415D749F328F663','F63871FD5D421701','81F2D8A0475D9F19','8B651F4661034D1C','6415E2B9D539CD6B','38263D4E38FD5F81','96D73F949872CC5E','4B1231520F27D0C1','4B1231520F27D0C1','6E7F78D5713D43C7','704FCFA486E7E149','18EC7612C41651BA','18EC7612C41651BA','C3F46DB0B212F747','CBBF81E21474810F','CBBF81E21474810F','2BCE01B8D2FBF1AB','0F11879596E8407B','75678D3ACA155B2F','9B0EF0F520A7DE3D','BD8BE58F85DC2EF2','F739B7FDD8765843','7D236785A1652B0F','6D7C41F3337D4807','F12D8850C4BFF6A8','E09F5B1FF60C8A52','B3F450941F3243CC','48F41A1773C03373','1F6E6520FD1562EC','ED5C657A702E541D','FEC365DD618D2750','F418FBAE0D067E5F','022391D6801BDF8E','BDF1E611130D8AF2','378C327C23F03A76','801A0D5E2F102228','4F50D29F27A18C09','1D36A032DDEC81E2','A66ACABA114F7F1A','2252D1627C7D35EB','959FA23336B03712','55B25A89364AAF88','7D1888F38B69DD2D','4D9EDDAD42E0F254','4147CE95654D1404','863674079326748','27F80B3BE0BD6362','87163F0EED074A82','A92AC1E73FFB9DF0','1BBE0CFC45F7E0EA','1BBE0CFC45F7E0EA','869137062507801','869630058898572','5BF8278F927CF253','74C8DCEB149A4EC7','A8ADF352DD530EBD','056560BAE7823948','E057492E62990146','E038977481883F3A','E038977481883F3A','869630057437810','1E06735E62EF60BA','40F7B54BBB1E04A9','3CF9CCDDE412C85E','99B5ECF4658E3668','7296E383247EAE47','863674075750891','058866B555D738E5','058866B555D738E5','83964DB9FC47D3CA','717F2A471D02E9C5','4715D769BA0DD414','EEC50FD1117A7F2C','3A69135E1C04E4F1','DFDF3A66E7FA2A64','02B125AAB8E5B2B4','863674079802862','869137064928427','944F2547B64412E5','9E8072EDB6795161','51780DD6B404CBA0','C4C38F3E07F35429','863674079446793','741BAB70E82AE3FA','E34B17B380C5C55A','7B4A32F8EB83046C','863674079806566','6954875CEECE2443','41B6C50E9A1E09E4','F64A756A3DE686A2','F809DEE5A372749B','1FEABBBDE2AF244C','3372F0A144E51B0A','038C863CA32D538B','D3C747C72ABA0385','5FF118A3F40E94C4','083BDBE0185A0656','863674075747921','863674079808133','7D95F5E2E3F4BEA1','FDC68884D9DA6F69','634520F6BDC9FBD7','A1B1D856E98CC19D','119552463E16A19E','143E394D60DB64FC','A18BCB8769D9EEDB','B0AB8FD3F8749AEA','4E3876F5A222446C','80518387E322E229','1A851E26E36D6B96','BCF364F8268529A8','A81204A55BD4796F','9F350DC5BCD06BC4','D68EAC6D75935A4F','869630057462792','B7ADCCF4D55D4341','9D17E031D4F8580F','8D354A9E98872526','83C440DA3FBBC059','1730795A8FF8BA4A','869630058220884','EEAF8204883F95BF','4270F405E3A4A602','864710056643991','EA9136D9CE958E5B','863674079393243','058EE7B6A84BC0F9','648FEF2F0C7D5326','EDCAD84CAF787460','20734ED8B6998AE9','4C0E52AE58C413A3','B90B522631F5C6E9','33EC351CB93AE18B','869630058397229','869630058397229','1F766243B4178ADC','989DB2382D1AAA06','5ECC54B6CC81432D','72754333CD9B8279','A134BBB73EEDDB15','A134BBB73EEDDB15','BB3EB64368B4E3DC','A37AC1651FD12401','869137062677109','4B688F3138B2550A','4175DBA4D31390D1','172B3FFC6F8C10DA','AEBE76D9ED7D71D3','82658BFCB2AE05D4','48046315C7E1E6B2','84B136DE217D7778','D87F77724913F6E3','96E54E9A483559D2','BB5E41625C19F334','1903CD47809D6CE5','A1B58075C3D15546','72D5C7DACC6FF112','9F067F93D70515BE','4E3B5358CBDFF870','FDF150BC164191D5','FDF150BC164191D5','1AF833BDF59F4D4A','F4415F28E0FC659D','F4415F28E0FC659D','4BF21C952A17A77A','49CBA2F3A1287F51','C36CA5CAA20707A5','1ADE12D3CB774426','FDF791D41DE9BCC8','FDF791D41DE9BCC8','217D1D0C3A027724','4379EEB418226116','FD2A076B73D740EE','1868796AE335A6DC','9C7A9220A272FC7A','685E278C921EF931','8233B34A8AC25E22','E4EF5076F62DA43C','749DDB1B6661920B','061A9FB7DBE499D6','2A04ABC36F1C219F','3ADFB69DCEBCAD49','4F05094FDA23A2D6','85310686482DB4AE','F5971DEB10A74C93','2FF603894DBC6F38','EA99478FE40C17DD','CD10BB0ED532B8C0','8B40A8CEE2F0D4E6','863674079768931','C07AD9998F7FB2DA','19C7D797867EEF19','B656C9670CDAD6E2','BAC2D4F77F6F3E31','23333104323106AF','A5F30BBB2FA50358','6D0CE39B944C9225','F6653391397F861E','B27D253CF2A08EDF','869137064924764','D198596DB9AF9C58','863674079776595','21719D8743D8B102','7665843C9E83FB27','0CFECC2DC665873B','39945F3462B4762E','869630057382867','98599FD51B0DC1B6','5510F1729CC78106','863674079430912','863674079764708','06AF5C4987A26E1F','869137064948581','B483CE2434530211','863674072241282','8B0E675BA808DD2E','19D63EEBC55E4096','48496A71B86276F9','42CA8131EAD429EC','F4763A20DE0E8070','5A3CD845205B3B35','869137063556187','3DB1E2C237A0179F','41A5FAB79A4982BA','26740E57E3400BDA','9462B06968D9435B','D58C2ED578D81E78','24A21A0DB278ABDC','19087DBA58180A0E','10EA6AFE4BFE392B','B5E1981F2651A637','1E9F5CC31FA19446','8F718C5823D4A108','41CE93DB220C9057','8EA0DFCFB190BE14','BB88AF19C34D145D','8629B46633BB6E69','F9770BDDBABC6A7E','85C91D0CA4829009','397D1B1E7C563B6E','397D1B1E7C563B6E','4B4CAC6BB4F04BFD','5810DA0908C61153','869630057637195','B883B857A27C1D56','F005B43620B529D7','4CFB7B8E599F67FA','78732666F3631908','2FA10CE52D939D9E','FA7F8FEC373E8068','869630050600943','864710056649352','FAEAB72A1BBCF33D','E2C0CF117FEA5E9C','4B771AD38CC6F28B','1D8D610E8D61D8B2','15296B738CEC79BA','863674072237009','71DFD523CA493CD5','869137061478582','869630050610298','863674079399083','863674079421671','C13933EDDC7E6EA1','869630057635785','C534661BC02B5DFA','E2903FD61C781F90','2F769B919FF66BB3','2F769B919FF66BB3','186BD17150B88B75','9E42B9FE52541B70','BAFAD4E9FCEA3ED6','3ADE01DDE5A6840C','4B4ED5DF4372970D','29EB27FE31E1A8B0','0FC7F83262D8CFFD','5CA5086B0924FC30','DC4B47483FF74ECB','B487788E63935260','49ABBF95FBAA10F8','480D31991AD94BF1','C2C062C9ED304728','1372EBF4C626E279','402A908ABB30BAEA','96DBB32ECAB8F3BA','869137062657051','62226465B84D7928','78B121A8F36276A6','323BAEA6578BEB36','C2BF6BAA5F18419A','53B174BE65449E4F','5B71D08E84D0A15D','3506B504618485FC','69C920D9C1FB25C8','A98BDE80F9432E23','A0AF7D5DE651F6B4','4CD23C1840E04C90','214BB180E4037239','9A6AED26D73C3B1E','5B4FDAB7C53F3CD1','758C5371B02DE5FD','3A43419DE9807B3C','D07E65872577E461','D07E65872577E461','869630059308258','BC6BDEA8EA4587F0','32E5345FD0086965','863674079377949','94D29E0C780D81B8','863674079780720','4A2FEA29AD1473A4','09D256B8039CA0B0','B3AA6E1F3B14A8E0','869630058326749','863674079407464','5A7CB916F36CFCE8','89611DF20B650687','58E530FCEEBE14DC','79F15F0D97E1AC40','831F019FCD095294','FCBF3C38F97A7B9A','FC53FDB1DBC96484','B9F8B7971740D51A','63BB8E7D8D586905','9D826628A906A2C0','64BF0A498F582F75','2D203487FE1C6F8A','6C31CF7DEF6A3638','863674075785012','DC4CD15AAED13E21','F3CFDC3C69137854','77FA450768557393','869630050636061','2EEEAED0D9F95DA8','B63E761AA32B90B9','863674079396204','2262D309D1A0DD77','2262D309D1A0DD77','869630057460721','19D3AA3AAAAB85EC','863674079409734','863674079409734','385F901B88E96436','869137061475281','869137061475281','869630053979708','165B494168482182','9B402A29814C483E','9B402A29814C483E','0B606C5F67EE97E9','93C1D3FA73072ADF','CFB501E3F512A968','CFB501E3F512A968','051FD315E94ED20C','1C16C9E647E6ACCF','26F4C51EA139EA2B','26F4C51EA139EA2B','C8FB673962B9EF90','022FD3DC1956DEA4','298253CA504153DE','14B012C4B090C348','78623D147B5B8D18','491FB1020EA11D92','2EDA213A8EB779C0','D97E77A76A477A0D','66EA5A9C021004F5','057C61C8147CD033','B8450FBCBAE212C7','279290151692B8FE','E9B650D7D70785CA','59A176DA813950A6','345EB923150291AD','C67396C6B7E59993','3CC6DCF3B3FE40B2','3CC6DCF3B3FE40B2','FC1392608DAA26C7','6D5176345C077758','64B3B32F76183D2F','D41BCCA2C48D249A','206B78E81B8583B5','74C14F92B350DEB8','7A1475140BDEA527','BDB8D540E4DBBE77','DD9C831E66CDB4A7','F01F74051671CE72','E6CB06E6AAF860E7','D48A882303D31E8F','E1059043B0740CA1','C93C29489FFE53BE','F40F01E0C51D9DF6','0633779BFAF5BC64','E86657A9ECE3116E','F3116D645BCB35D1','25327C2ABDFD1504','8EF79486827B554E','5D6CFBE7374B1EDD','2979A8B30A516873','42296265CC92E91C','F42256086C234958','0E68F527F1467502','0B17FEC0D0D48C78','96422E51E5A1CAC4','1420F506B2ED181A','BC7AAF88F592BBFB','EB3A620BD612D74E','8896514A7C85AA6B','0B7F70D8FA4F651E','FA27142EA6FB84AE','F0EFE127A43684EE','0746804EF6256644','B03848FC697341FE','98F29A3A0B077E09','348F5112F88D0B25','903A581769602D85','34EF5FA0164D326A','3F7A7E57864CB703','6EFB2F949B420A69','2C684824A0EE95C5','C73F605CB9E623CA','570EE2FB4F770ABD','EDEF518CE5AD1520','FD1833C4F227E73D','6C388F9463D7242E','1760A69314E85003','EFFC0C7916AC6BBA','D1CE73049C61EBFE','CDDDF710CA9A1A1B','203B4344C90B0304','F0271F9A53D507B0','5B7D7E9F3F12DECC','C86C48D52DA50EC1','0692F393B0B4F0D9','5E747BFC5813AE9E','C0D2EB9320110D85','15849F463DDADA8B','57436DEC38E6ED29','59D45F4E03480EED','869630057433090','7D60A18A19EFBBE7','BBF745ADC44883B0','3BFBACD564FCF98F','869137063559587','1EC6F01586FA0727','A9593C1F1B808AB0','BEE68B4C993E0404','DC5CB9CD06F71259','87E101A788453E80','11412F331EF3858F','863674079406961','16498D55C6F21BF3','869630057424669','549778E74C5C4F07','A3B9DEC6AEB9B4D2','845A1D9D60815D87','371BA507AD5DF4FA','3324ED7181CE3DE5','FD1E468C5C31728C','5DC86EC6FC5175CC','C67F72956087629D','586311E943F6A4F0','D99E3BD14A562775','9991142523634E5A','106BE76BFEC44F61','C1924497F4967C16','3DF682967DD2FCC4','F43D5073385F3044','69BDCC52DE2F6419','F45D36B90FE0E5AC','2CBE739BF74C5A0C','300484763F83A0FE','869137069210391','6E62508457DD9D99','6E62508457DD9D99','693CE57C598CCE2B','863674072248493','D2B7ECE15493E9F1','A5CDD25B3687B234','84AE71935340D5E2','1051B873C5749040','9935C925869352F1','6B303BBC4FD8A38A','C177A7C967CACE3E','F02DA20AA89EE124','863674079782874','864710056657025','869630057446779','70A8FB1574F1E73B','3A9D8B7831E1144F','CCF3F549227661B4','DBC1B1D425FB5EB9','1213B128E0EB8121','21121DF668038A35','C21DB7DCA7DE7081','BC01CD46FEA4CFEA','F510A0F109A6706C','C560794316D01952','6011B80C94D12743','6011B80C94D12743','90451FE320F4FDE3','3ECC54F3985E8225','C07337C495C027E5','C07337C495C027E5','91C2441AE806C4E8','869137062503115','4AB571340F0D523A','4AB571340F0D523A','3AD5478DA09B9C64','8EA055C9453853F6','8EA055C9453853F6','5C04F181C48BA3FB','1EC1C4DB6F5AFAF3','863674079414130','67335DA20E2434C1','A710626D282CDB1A','56A9A20F3C192696','2CFC0E30B603F228','2D292DD953A938AE','869137069246593','475CC5865813058F','33438889F70391E5','33438889F70391E5','33438889F70391E5','07447F886686E780','4AD1308AEDDECDD2','4A9FCE74016AE86D','973186F229542A06','C56D99F90D3A217C','9B1ECA35CD03B52B','9B1ECA35CD03B52B','100A586766E88F49','71D045DCBC438652','14011EF3EFA1F438','090BCD45E1C27215','A7CAD046CFD725A0','BC876053A68D83A1','E355D23C78925288','4349CCA137D96AAA','76EBFA9A3EF5205F','37A9A0E8DFB1841B','B1DCF664B163CF01','7EB3563801E66283','3CA42909A11267BA','02C591A0B25722BC','05EBE2E87658ED25','05EBE2E87658ED25','85EF11D9E0CCF3D6','85EF11D9E0CCF3D6','1FC5D5A2A2615325','77C324FBDD4CD119','F58EDDC88B36E6D5','B7155820BC852CE3','EF1E7FA4A8C07FC0','EF1E7FA4A8C07FC0','B1E52F60DEA789D4','36A84CBED9CE615F','2D627F0A1F069149','FD46C1CC0EDE7452','D875705F8EE5CE81','1A351624E14B9663','1C771D83E4F1D9F4','E96ED79011F1F45C','FE81F968F4696636','7A38CF948E1EB8D8','FB9A36D91F31072F','82CAE82BE1CE912C','D8EAD4786A19B3F4','C5B2BEDFD8C7CF19','AEE5CEDFBBC7B17A','56135509315EB33A','9F76B5D499D71132','12B782F5ADDBDDD2','115F8C5EC1C1D8A1','869630053987289','EFAACC415E6BB0EF','9284CF81A338165A','1368684202577A07','FDE56CDD11EA0D3D','B04E7D2E14388CB1','70F80CA08F8C2A0D','869137062730403','42F3F5D9B7B9A83B','56A5660A4F9415C1','25E82C04BA57796E','5249C565248BB179','68B72392D73091F6','1DD4896A9C9FD473','F961C288B7F5624C','863674079434336','3A6CEFAD638653CA','ECE952E090AB43E3','1BFA8A1FB11AF954','25356EDA32049DB9','ECD8C18E34DEAD6D','981B511E113BAF4C','C3781BF6649257A2','B062784201F1422A','90B47A8FD6EC87CB','038B572804D5D419','863674072267352','A7F13C9113A02B8D','4452839F016F3AC8','668C3713BAD6ACCB','4B269A6FDEDBD2BD','869630059468318','0E2939B70249579C','B71F51A8C43372D9','CBC3144A03CB5C0F','5F7E8BECFCEA52E7','3F77EF777FABE2D3','D8F99CFB75B4C5B9','3DF908CA4ABEA182','DACCA248DA419587','667C12C0749F1CC7','CEEE071ADBC7A928','7FA7CBD4FEFEA5A7','863674079784300','184D7C5AECEC948A','DF164D03D72B7708','0D781E67EAEAF847','B2D3AF329DBF4E11','F95165026285B71C','4B6D4B3B14869E83','C269BF025F4DB004','FB79C84EDD6998A9','F471FAECB7135A04','3F7F157D6CC2DE80','40F9259CC71BD5A3','37B0316EAE04039F','CF4D3E2E76B05D8D','CC5E442299FD6A37','5B657B0ACE760302','ED21599A96AFDFB3','17BD01F56FAC53F6','38B5A42D837F4904','96123E09E8236B9A','0DA9659CC358D2B6','65B8BCFA8FEE4C2E','DF969CDAF56C71F0','863674079784797','869630050652340','775323B858406A9A','DA8F39729FDB3FA2','8EB20D637E12DDB2','4EB6E0EB096BF56A','AD2A45610B6D20BF','320994CE4F6291A4','320994CE4F6291A4','F28DEC65AC3CDA58','087DF8FDC49668BA','863674079442248','863674072252354','863674075739977','63480A0C9C45F819','ADA24CF482138020','C4DF79A0D878AA99','89D78C954AB20B87','869630054350628','6504DA585CEEBFCE','869630058783485','869630058713029','1623055B16600EFB','D6537370C868E032','E1F0B08A042EAD61','A86EC6EA4ECDC80B','233CF1228B658562','3F9B44277DF472BC','863674079414502','863674079797187','7164CD0984B0D3B4','35EAD7722E657BEC','B6D4D003FDEF8083','D0A01A7E294DF383','99A0356993F991A6','BE5308A4BB12A332','11158039946D48A8','CB8C148CDA1B7CB0','3A5ACAA00846E90E','D16E317B6DA341E9','D72BCE0CE43187DD','1C41505A201CF2F9','BC3D9E45CC0B71A5','AFD162C34373F279','869137069168896','E81F6B23C9A4FC28','BA4287C65D76C66D','52D5182B3BAD779B','2442C9F1E04533F5','BDD566353D587042','08CB480D93F5EE59','81600A7C90875151','213371E01571B734','7BBEA760060C442C','F6923FB5537B5A04','8708FC10CD68FB7C','8708FC10CD68FB7C','869137069187128','869137061592440','DA03F391C89ED2EE','E1165014425E98D8','A96F3C2ED034CE69','EBBEBAF92AC58E4E','E87CB96A0F7896F4','83DB2EA11AC31809','7AEE8C160F8B50A2','8BC3BA10C36F335B','E8D474D1C8338163','F8E1196CB4314B3C','9B85B02C9D6AD206','9269ECA5FC8E6481','953D4DE27BBC1A9E','5BB7236F90802FF7','5E0D44B4D15840DB','869630058646211','DB81EEBD802C4870','9AFE2F1757F1B0D2','8B5F1253FBF278BF','863674079788368','863674079403182','3DDAF973FA3E3F6F','A6F6EC20141E5FD3','F8EAB2093DB0706D','863674079448542','1FFA329407046D5D','27BD4243656DF356','01D6E5248519D915','498E6A6638BD1524','F5F53BAA22A8C8BF','869630057434635','8659D42B277F8D94','25844F8EC51A6F62','8B77C6E6DA59D6CE','3815DAB2052991AA','D3C6DBE912DD2CB6','1625C0E1B006A887','17BC7C32DF4BF3F0','372891A39D02C3DB','864710056651275','7967D53AF86695B1','7A1E87A2EC8DAF26','606FA55F45217A6F','0FB96E3FC82B800D','53DA08EC7A2367CB','D41A3E720B308D5A','5BDE2FCD1FC990A0','561E841AC06115CA','283C014C629EBD96','06AA46E1345468E9','7CF0DE9FE3265061','46ABA27A326885CB','E20314A6AA9645A9','3688EFC2F6942439','968EDD21D754A431','144EA06376740AF3','50A0E84C292DB578','82868A337C997B5F','869630057621637','2C16EA12B2AEF902','ACD350E403A85D26','3C0522C6CF14D2E1','A624B0E2DE1A19A4','E0B61F48BD380BC5','863674079396634','2FA4BF728638E25C','C61A0C5F5FB1CC3C','869137065090326','C50F1FAD5572399A','869630057437190','93E9E6E19EA9ADDD','51FBB53192AB2661','51FBB53192AB2661','34C6BB5AB30ECBDB','440E23F522281ACA','6E15B77017614024','E63FAE7058677342','0CA6ADB6036ECD4B','12C3813D57EAEDCE','B18BA0622B06BB4E','869630054354174','E1B9C959A26662CD','F8C70E3797550E8C','087BCAF69692B6C2','863674079347447','9CB02503B5839C77','A87E7E50D38A6F0F','CBBF94CE5DEE20A1','F6F762A4AB5BDF39','1138D994811CEC2C','163B9ED339F5BCCA','F91B56B37798E2E9','126227C2CBEF4ED9','AD21CDC66FF66F32','8E632C493EF74A0C','E420723BF934B2CD','F532DA3DF838AE02','F9C38757D0739203','45ADB65F57BD2187','869137069125912','D2D89C40B6956C58','849F04A217EFDACF','3AA5A64DBED8C296','869630057387098','7B269F7C5D176A75','8F2DB2CFA7A1BBB4','E62BAF056AC0C1FA','DFA85EBBA3152CE7','869538A455171901','5AA64521FA8CD921','D5D5E6898FA03CF8','C5EC73BE43A435B7','869137061572053','73BFBA8B0774CED5','19FCE97EE0CA5BA4','938C6D39573BF5AD','766C8E547EBA4BE6','863674072256652','726AC060228832F0','3BF74EF00BF42081','D7CDD4096DE3ABFC','C823FDB9BEA17C22','53E5E14664A39F06','C2040A16C4C03B3B','1951C9F7574759E2','E9A1A4034A4290CD','F0FB352262783E80','6F9C2F25D237782C','9DD9090F77D9993D','F01D471F23C829E9','919F48ED17E6A221','7AF528C2ADA16B31','7AF528C2ADA16B31','B5CD52EDB122FA78','3AB13D9A5D25D7A2','EFD8340BEAB0EADA','EFD8340BEAB0EADA','8B6B31718B314F9C','CB3246A4B6827C1A','C9B28DF89A5A9C89','CCEF8230BFCF8468','A7D2F5EA998F509F','69469BB75E481AB4','863674079773436','863674079773436','EEF8653AD6034DD6','869137069205318','E1CCF22553BBED42','311FE7277507AD2A','DEAFC3AD383DE336','869137062683875','C148F8FAC1A203BD','307A41026A9F8DD6','30776CEF79CEAB99','5DADA80994EE7588','C2AA2B9F4DAFFE58','863674079784326','7104CFB895EC132C','3A88DDB6C62BD4D6','D180F57D6D0EAA31','492B0A37CE757989','341B57D44EEA5A9D','A568F8B181224E2F','F3EB2142C72D4070','F3EB2142C72D4070','761E6962BB078C62','F9640A1A9C4B19A1','E5E278EB7D154E01','684F344337CCF0B3','869137063599419','5F6813B624126917','3079538A8F736150','B8099F4381C1AEA8','3CE0A07DDA8FBD4A','3787EDAE25B3BEF8','965FA2B9939438F4','689DF8625A31C54B','3C2CC9DE9789A8D6','72BE24D2C66FC428','869137069165694','DEE7961469155136','2CA556DD5BBE96C6','9B7A47480C76A39C','78A4A0B868D9CF0B','99BA58D60822EF9E','C5FDD9BE1967DEAE','60F704EDA1692D9E','863674072215690','572F7A8BE8BFB434','A28D8FDD59977B19','863674072237751','863674072237751','EEAFF8F7D482F29C','CF8819BDDD607152','4D5B0D5E5FDF15B9','98237F6E8649BA52','79C1721A5FAFA70E','863674079793426','72E3CC0963769BA1','863674079798276','4FEB58721627FB12','342E2393DFE769BC','B8956B0E7330D3D2','863674079336358','780E1DDC388484E1','2D862A9B7CAB818D','CAE61F22A449346A','AC1EF88FE6A19ED1','CD8AF5B92D0C466F','2E0DB65FFE65788E','CF1F442FEE792F41','0EC87464AE9A7D72','7B9A034EA2E021C8','A0CB6815290DACA4','42365213D8622FF8','0C6466E4E3F7657C','2930884126DCCBF8','2930884126DCCBF8','5263795ADD788EF7','5178F7942E97897B','4A640390DB5C0CB0','A56BD8D270482F9B','E8DF41990AE12C01','F3EC18546657DEA9','863674072257569','B31B1FC0621C8336','C56592FA0804CB76','C56592FA0804CB76','7E803A2638015EB1','589AACB46DB2CA61','863674072263146','863674072263146','5804D6322BD1ED62','B51D411771C4063A','0C665736991092FD','D86685569446AEC5','4D3B60045D5BA52C','C075A08C147D852F','863674079769061','CE63256CC6D2BB45','ADF738A4EB9D5647','863674079422117','E55F3DD525FCFAE3','C92A289B9A704466','863674079421259','28DF42172179BEB2','5D60CC5DC71E7FA6','863674072209248','E61FCDFBF9DBFC99','A276E58E551ED137','40C7878554468F6B','863674072261744','0D6C4F62D0972E3F','B60DC84470E544C3','E1140962F7ECA532','BF49A99726D9DADF','C105B0E38B5ACC72','67DC23799BDAED91','831836EEC602C733','B1FD5FAFE310CEE9','463439150BEA925B','EAFD8530F9950B53','C2A667E656E41B22','8659A88E05441095','22F0E7CB4CBE7858','73CBA4BB6DB4B79C','37966C644F471588','4F74582FAFB612E2','18A00D629E8D77B4','3DFD9B485D8F3AE4','CF1EDF79F80F3DE3','68A128CE2C07A6F8','D5169AAE43F6BF35','5E3CF0DBD08F7D13','DCC14F5FDF36041D','0685AD5D883A64CB','9363BA1C44CE0DFB','226F47543FEC6361','226F47543FEC6361','863674072208927','863674072208927','CB3C7778EABC84C0','24F88542EB728981','33F9E7CC6EFBD025','85D2C7ABDBA5CD76','5AF0112BAF25F920','572E4E9923482596','8F2521D7F4AA7F16','3FBF34E61E38DF01','863674079440523','869630057435525','F8F86FF8624013D1','E565F8D335C1B10F','D17433CF3171125B','726425E1ECF9FE4C','869137061552626','863674079330591','2A64120643B55B88','D148821139A6E14E','90B47A8FD6EC87CB','A1010393DFC46193','2571A641F1F63881','4A4C8F97CE5FAD86','E1CCF22553BBED42','8A28FE76C6DC01B5','863674075746519','DE6AE38716A05112','DE6AE38716A05112','372E79CC21432D1C','789BC9CAD364BD6D','422BEE4FF3D49319','863674079355903','A6EE9893DD2EA173','8B1FF52451061D84','BEB507BB6D98A369','86D2C94ABDDA6FC2','F5884BC2D962EBA0','BE31E96D8024F3E1','64A12B6413038603','51A8C707DCC258C5','CA51FBEE916E0A03','C325199B8C3F482F','7DF0FE6B313F7196','D858064E63B22BFA','32CAA7929AA75EC3','DACA2667F04A20A9','C3DE21E54F831AB9','312A1D8D247613CF','D41A3E720B308D5A','E6CC82FE85B86EE0','70F80CA08F8C2A0D','03681BB35FDAAD3D','F5443E7C1C995F41','78FE3B5F7562B56F','84A4FD528D445FE8','05585B5247A34690','9DEB3BD2BA9BDAF6','597A0522C69269C1','01A27AF67C357DAD','D1921997F1DA073E','1079799977EFE8DF','6FE50625A730D708','9139594DC98FB26C','D83721CEF11C28DE','618DB4732E055776','0B49985232963474','D5F97734928995A8','C8CBAC57AA1351A3','3BDC1628B74CD1B9','B0122D38319F98DF','38B3A98C82AA493A','688FE7C155CA7564','F2ADD71F3002D8B5','B9838651073EDECE','5ED32D083CBDA9D8','4D0BCFB3F168DEF5','741B32C19EC83236','DF0975449AE83A71','DCC23D88783B4732','6713EE6DED65A278','F668C878DBF0587A','9EA2F81DD0C243E7','3A7D210421BB416D','19DA871DC5EA5190','3CDB92CE2EF6F2EF','562599BC28C6AF5C','4038FADCC6320797','B19C4810F5DA8BC9','2E0807971A02D814','BD2DEDDE26430A16','7753CBBCBFC4CE5E','7A9BD930E2EF18DB','3325736BC1E8140E','74982A172A8CE7FB','1988D0A6A8C3F5B2','629934BD80624128','2B6CDB43457BC820','D79376AB9CAEB0FD','7D6E0F6BC9DBBA0B','1C12CC56A439466B','47C626CF7848AD94','4E40C31678128F66','334AA606613D21C1','F49DA3724138824F','2D6A213BB267D91E','6D34CFE1905EA039','FE72FDFD045D67C0','C0049475E20CFD26','0CAEC60AA3B2C97D','28A2656B3F37647B','107D7931EB97DE31','888D53EC03EDF626','9A25351C58A06080','FB238A807C9A7618','B735F3940644B652','4AF5E2F840669D59','839DE7A2B2C78A53','45F598E9A343DFB8','6BF3B98F18833465','9D2C82C45957A254','A63A109B6A98DC4F','6D2A13915CAC361D','9061655EDE2FAE9C','5652650CC5A92CA8','2AB8C581DA73E0C3','6539F9BFB4B5A82B','ADEF214288FC66C2','126B7045D6FEFA53','259FA64CB70E441B','CE23A0BA463E68B4','0C9B3B08065BADAA','B244D6C0514F922D','51B7D12D5910269C','7347217BB85DF63F','1CA501D4AD8EB21E','4BE7EC0D57530779','2F10CF1F6224EF1F','F8C4EF693A79126A','BBC052678435B8C9','BEFC6BF64375C372','5F219D9D51F82370','F34BC7BA190F6E48','959A8BEF11DEB324','CE99027B50816BBC','B8C1651F6E0356D9','99A0716344B8589C','FD93F50E3C761D77','49AC6C708C0C4F6F','BBDF3E55A07E68BB','DDD84AAC7BEC4C30','A1C440ECAB76CBCD','137DF37133EB66B1','137DF37133EB66B1']

In [9]:
iot_str = ",".join(f"'{iot}'" for iot in iotList)

batteries_df = prodFetch(f"""
SELECT
    zoneId,
    iotDeviceNo
FROM batteries
WHERE iotDeviceNo IN ({iot_str});
""")

2026-06-26 16:42:30,520 - INFO - Executing query on MySQL DB: batterysmart_prod
2026-06-26 16:42:32,033 - INFO - batterysmart_prod → fetched 8739 rows

In [10]:
batteries_df=batteries_df[batteries_df['zoneId'].isin(["NMP03","JHR01","JHR02","KOL01"])]
batteries_df

     zoneId       iotDeviceNo
4356  NMP03  973019C482B905F2
5887  KOL01  206B78E81B8583B5
5891  KOL01  DD9C831E66CDB4A7
5898  KOL01  0633779BFAF5BC64
5899  KOL01  E86657A9ECE3116E
...     ...               ...
8728  KOL01  F34BC7BA190F6E48
8729  KOL01  959A8BEF11DEB324
8730  KOL01  CE99027B50816BBC
8731  KOL01  B8C1651F6E0356D9
8732  KOL01  99A0716344B8589C

[82 rows x 2 columns]

In [11]:
batteries_df['iotDeviceNo'].nunique()

82

In [12]:
device_str = ",".join(f"'{iot}'" for iot in batteries_df['iotDeviceNo'])

In [18]:
off_status= trinoFetch(f""" select * from iceberg.bronze.battery_immob_remob_requests where iotDeviceNo in ({device_str}) and status='DEVICE_CMD_EXECUTION_SUCCESS' """)

2026-06-26 16:50:23,947 - INFO - Executing Trino query on iceberg...
2026-06-26 16:50:26,524 - INFO - Trino query executed successfully. Rows fetched: 121

In [20]:
off_status['iotdeviceno'].nunique()

78

In [21]:
actual_status= read("https://docs.google.com/spreadsheets/d/12kPyTZb1PILSulIN6uITJwy3uCvg-c8TJtgFd9UEZmw/edit?pli=1&gid=1081719555#gid=1081719555","rough_1")
actual_status

2026-06-26 16:51:59,832 - INFO - Pygsheets client authorized successfully.

,batteryId,deviceId,manufacturerName,serialNo,mosfet_turned_off,action_timestamp,action_date,receivingId,receiving_time,driverId,...,api_failure_flag,no_event_ping_flag,sink_flag,ts,txn_days,service_days,recon_days,chgDis_days,phase,batteryType
0,B1000202,246F4B3F82B5A214,BATTRIXX,B112004420_131931,discharging,2026-06-02 16:16:42,2026-06-02,65965387.0,2026-06-02 18:27:59,D264188,...,FALSE,FALSE,FALSE,2026-06-24 20:52:20,0.09,NaN,NaN,NaN,2.0,LFP
1,B1000852,80D52CC004987C7A,BATTRIXX,B112004450_127601,charging,2026-06-24 00:08:37,2026-06-24,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 21:09:59,NaN,NaN,NaN,NaN,2.0,LFP
2,B1000872,20327703C839920D,BATTRIXX,B112004450_127580,discharging,2026-06-24 00:07:51,2026-06-24,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 21:10:10,NaN,NaN,NaN,NaN,2.0,LFP
3,B1001391,2726E6DD6E7885C4,BATTRIXX,B112004450_127984,charging,2026-06-22 11:10:26,2026-06-22,NaN,NaT,NaN,...,TRUE,FALSE,FALSE,2026-06-24 21:09:00,NaN,NaN,NaN,0.19,2.0,LFP
4,B1002233,9C835D9FACCF1C3D,BATTRIXX,B112004450_128395,discharging,2026-06-22 11:15:11,2026-06-22,NaN,NaT,NaN,...,TRUE,FALSE,FALSE,2026-06-24 21:09:57,NaN,NaN,NaN,0.12,2.0,LFP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5907,B999505,461FCF3311E51E77,BATTRIXX,B112004450_127104,discharging,2026-05-31 22:58:05,2026-05-31,NaN,NaT,NaN,...,TRUE,FALSE,FALSE,2026-06-24 21:10:11,NaN,NaN,NaN,0.65,2.0,LFP
5908,B999505,461FCF3311E51E77,BATTRIXX,B112004450_127104,discharging,2026-06-01 16:11:22,2026-06-01,NaN,NaT,NaN,...,TRUE,FALSE,FALSE,2026-06-24 21:10:11,NaN,NaN,NaN,0.87,2.0,LFP
5909,B999505,461FCF3311E51E77,BATTRIXX,B112004450_127104,discharging,2026-06-07 12:22:55,2026-06-07,NaN,NaT,NaN,...,TRUE,FALSE,FALSE,2026-06-24 21:10:11,NaN,NaN,NaN,0.09,2.0,LFP
5910,B999505,461FCF3311E51E77,BATTRIXX,B112004450_127104,discharging,2026-06-08 12:18:28,2026-06-08,NaN,NaT,NaN,...,TRUE,FALSE,FALSE,2026-06-24 21:10:11,NaN,NaN,NaN,0.30,2.0,LFP
5911,B999505,461FCF3311E51E77,BATTRIXX,B112004450_127104,discharging,2026-06-09 08:17:02,2026-06-09,NaN,NaT,NaN,...,TRUE,FALSE,FALSE,2026-06-24 21:10:11,NaN,NaN,NaN,0.95,2.0,LFP

In [22]:
batteries_df['iotDeviceNo']=batteries_df['iotDeviceNo'].astype(str)
actual_status['deviceId']=actual_status['deviceId'].astype(str)

In [24]:
actual_status=actual_status[actual_status['deviceId'].isin(batteries_df['iotDeviceNo'])]
actual_status=actual_status[actual_status['api_failure_flag']=='FALSE']
actual_status

,batteryId,deviceId,manufacturerName,serialNo,mosfet_turned_off,action_timestamp,action_date,receivingId,receiving_time,driverId,...,api_failure_flag,no_event_ping_flag,sink_flag,ts,txn_days,service_days,recon_days,chgDis_days,phase,batteryType
3218,B746083,973019C482B905F2,BATTRIXX,B1_51105_B_120205,charging,2026-06-20 14:53:04,2026-06-20,NaN,NaT,NaN,...,FALSE,FALSE,FALSE,2026-06-24 20:30:04,NaN,NaN,0.86,NaN,2.0,LFP
4768,B911661,206B78E81B8583B5,INVERTED,INCBZC5145E0075,charging,2026-06-20 01:16:11,2026-06-20,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 20:28:26,NaN,NaN,NaN,NaN,2.0,LFP
4775,B912048,DD9C831E66CDB4A7,INVERTED,INCBZD5145E0296,discharging,2026-06-05 16:19:47,2026-06-05,NaN,NaT,NaN,...,FALSE,FALSE,FALSE,2026-06-24 21:10:18,NaN,NaN,2.96,NaN,2.0,LFP
4784,B912820,0633779BFAF5BC64,INVERTED,INCBZD5145E0566,both,2026-06-18 20:32:09,2026-06-18,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 20:52:55,NaN,NaN,NaN,NaN,2.0,LFP
4785,B912825,E86657A9ECE3116E,INVERTED,INCBZD5145E0571,discharging,2026-06-24 12:28:38,2026-06-24,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 20:28:55,NaN,NaN,NaN,NaN,2.0,LFP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5869,B997846,F34BC7BA190F6E48,INVERTED,INCBZE5145E1128,both,2026-06-18 21:12:21,2026-06-18,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 20:21:40,NaN,NaN,NaN,NaN,2.0,LFP
5870,B997863,959A8BEF11DEB324,INVERTED,INCBZE5145E1277,charging,2026-06-24 14:11:05,2026-06-24,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 20:14:37,NaN,NaN,NaN,NaN,2.0,LFP
5871,B997872,CE99027B50816BBC,INVERTED,INCBZE5145E1291,charging,2026-06-24 00:09:06,2026-06-24,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 20:46:03,NaN,NaN,NaN,NaN,2.0,LFP
5872,B997873,B8C1651F6E0356D9,INVERTED,INCBZE5145E1288,charging,2026-06-24 12:27:52,2026-06-24,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 21:00:04,NaN,NaN,NaN,NaN,2.0,LFP
5873,B997877,99A0716344B8589C,INVERTED,INCBZE5145E1280,discharging,2026-06-24 01:51:24,2026-06-24,NaN,NaT,NaN,...,FALSE,TRUE,FALSE,2026-06-24 17:40:44,NaN,NaN,NaN,NaN,2.0,LFP

In [26]:
write(actual_status,"https://docs.google.com/spreadsheets/d/12kPyTZb1PILSulIN6uITJwy3uCvg-c8TJtgFd9UEZmw/edit?pli=1&gid=1081719555#gid=1081719555","B2B")

written successfully

In [28]:
B2B_df=actual_status[['batteryId','deviceId','manufacturerName','serialNo']].copy()
B2B_df['serialNo']=B2B_df['serialNo'].astype(str)
B2B_df

     batteryId          deviceId manufacturerName           serialNo
3218   B746083  973019C482B905F2         BATTRIXX  B1_51105_B_120205
4768   B911661  206B78E81B8583B5         INVERTED    INCBZC5145E0075
4775   B912048  DD9C831E66CDB4A7         INVERTED    INCBZD5145E0296
4784   B912820  0633779BFAF5BC64         INVERTED    INCBZD5145E0566
4785   B912825  E86657A9ECE3116E         INVERTED    INCBZD5145E0571
...        ...               ...              ...                ...
5869   B997846  F34BC7BA190F6E48         INVERTED    INCBZE5145E1128
5870   B997863  959A8BEF11DEB324         INVERTED    INCBZE5145E1277
5871   B997872  CE99027B50816BBC         INVERTED    INCBZE5145E1291
5872   B997873  B8C1651F6E0356D9         INVERTED    INCBZE5145E1288
5873   B997877  99A0716344B8589C         INVERTED    INCBZE5145E1280

[82 rows x 4 columns]

In [ ]:
# import requests
# import pandas as pd
# import time
# from datetime import datetime
# from zoneinfo import ZoneInfo

# # ==========================
# # API Details
# # ==========================

# URL = "https://api.upgrid.in/api/batteryImmobilize/createLimeRequest"

# HEADERS = {
#     "Content-Type": "application/json",
#     # "Authorization": "Bearer YOUR_TOKEN"
# }


# # ==========================
# # Function to send command
# # ==========================

# def send_command(serial, command):
#     payload = {
#         "serialNo": serial,
#         "command": command
#     }

#     try:
#         response = requests.post(URL, json=payload, headers=HEADERS)

#         if response.status_code != 200:
#             print(f"❌ {command} failed for {serial} | HTTP {response.status_code}")
#             print(response.text)
#             return None

#         data = response.json()

#         if not data.get("success", False):
#             print(f"❌ API returned success=False for {serial}")
#             return None

#         request_id = (
#             data.get("data", {})
#                 .get("data", {})
#                 .get("requestId")
#         )

#         print(f"✅ {command} | {serial} | Request ID : {request_id}")

#         return request_id

#     except Exception as e:
#         print(f"❌ Error sending {command} for {serial}")
#         print(e)
#         return None


# # ==========================
# # Current IST Timestamp
# # ==========================

# now = datetime.now(ZoneInfo("Asia/Kolkata"))

# action_timestamp = now.isoformat(timespec="microseconds")
# action_date = now.date()


# # ==========================
# # Send Commands
# # ==========================

# rows = []

# for _, row in B2B_df.iterrows():

#     serial = row["serialNo"]

#     print(f"\nProcessing {serial}")

#     # Turn ON Charging MOSFET
#     chg_rid = send_command(serial, "CHGON")

#     time.sleep(0.5)

#     # Turn ON Discharging MOSFET
#     dischg_rid = send_command(serial, "DISCHGON")

#     time.sleep(0.5)

#     rows.append({
#         "batteryId": row["batteryId"],
#         "deviceId": row["deviceId"],
#         "manufacturerName": row["manufacturerName"],
#         "serialNo": serial,
#         "action_timestamp": action_timestamp,
#         "action_date": action_date,
#         "state": None,                    # keep blank or modify if required
#         "action": "turned_on",
#         "CHG CMD": "CHGON",
#         "DISCHG CMD": "DISCHGON",
#         "chg_rid": chg_rid,
#         "dischg_rid": dischg_rid,
#         "lat": row.get("lat"),
#         "lon": row.get("lon")
#     })

# # ==========================
# # Create dataframe
# # ==========================

# turned_on_df = pd.DataFrame(rows)
# turned_on_df

Processing B1_51105_B_120205
✅ CHGON | B1_51105_B_120205 | Request ID : 426922_23
✅ DISCHGON | B1_51105_B_120205 | Request ID : 426922_24

Processing INCBZC5145E0075
✅ CHGON | INCBZC5145E0075 | Request ID : 608088_5
✅ DISCHGON | INCBZC5145E0075 | Request ID : 608088_6

Processing INCBZD5145E0296
✅ CHGON | INCBZD5145E0296 | Request ID : 614232_3
✅ DISCHGON | INCBZD5145E0296 | Request ID : 614232_4

Processing INCBZD5145E0566
✅ CHGON | INCBZD5145E0566 | Request ID : 635075_3
✅ DISCHGON | INCBZD5145E0566 | Request ID : 635075_4

Processing INCBZD5145E0571
✅ CHGON | INCBZD5145E0571 | Request ID : 614743_2
✅ DISCHGON | INCBZD5145E0571 | Request ID : 614743_3

Processing INCBZD5145E0613
✅ CHGON | INCBZD5145E0613 | Request ID : 616239_2
✅ DISCHGON | INCBZD5145E0613 | Request ID : 616239_3

Processing INCBZD5145E0767
✅ CHGON | INCBZD5145E0767 | Request ID : 638580_2
✅ DISCHGON | INCBZD5145E0767 | Request ID : 638580_3

Processing INCBZD5145E0821
✅ CHGON | INCBZD5145E0821 | Request ID : 619621_2
✅ DISCHGON | INCBZD5145E0821 | Request ID : 619621_3

Processing INCBZD5145E0868
✅ CHGON | INCBZD5145E0868 | Request ID : 615137_3
✅ DISCHGON | INCBZD5145E0868 | Request ID : 615137_4

Processing INCBZD5145E0889
✅ CHGON | INCBZD5145E0889 | Request ID : 615969_2
✅ DISCHGON | INCBZD5145E0889 | Request ID : 615969_3

Processing INCBZD5145E0931
✅ CHGON | INCBZD5145E0931 | Request ID : 614573_2
✅ DISCHGON | INCBZD5145E0931 | Request ID : 614573_3

Processing INCBZD5145E0908
✅ CHGON | INCBZD5145E0908 | Request ID : 615139_2
✅ DISCHGON | INCBZD5145E0908 | Request ID : 615139_3

Processing INCBZD5145E0976
✅ CHGON | INCBZD5145E0976 | Request ID : 615623_3
✅ DISCHGON | INCBZD5145E0976 | Request ID : 615623_4

Processing INCBZD5145E0985
✅ CHGON | INCBZD5145E0985 | Request ID : 615130_2
✅ DISCHGON | INCBZD5145E0985 | Request ID : 615130_3

Processing INCBZD5145E0975
✅ CHGON | INCBZD5145E0975 | Request ID : 615482_2
✅ DISCHGON | INCBZD5145E0975 | Request ID : 615482_3

Processing INCBZD5145E1050
✅ CHGON | INCBZD5145E1050 | Request ID : 614890_2
✅ DISCHGON | INCBZD5145E1050 | Request ID : 614890_3

Processing INCBZD5145E1064
✅ CHGON | INCBZD5145E1064 | Request ID : 613652_2
✅ DISCHGON | INCBZD5145E1064 | Request ID : 613652_3

Processing INCBZD5145E1039
✅ CHGON | INCBZD5145E1039 | Request ID : 615252_2
✅ DISCHGON | INCBZD5145E1039 | Request ID : 615252_3

Processing INCBZD5145E1045
✅ CHGON | INCBZD5145E1045 | Request ID : 614544_2
✅ DISCHGON | INCBZD5145E1045 | Request ID : 614544_3

Processing INCBZD5145E1088
✅ CHGON | INCBZD5145E1088 | Request ID : 601340_5
✅ DISCHGON | INCBZD5145E1088 | Request ID : 601340_6

Processing INCBZD5145E1079
✅ CHGON | INCBZD5145E1079 | Request ID : 614787_2
✅ DISCHGON | INCBZD5145E1079 | Request ID : 614787_3

Processing INCBZD5145E1177
✅ CHGON | INCBZD5145E1177 | Request ID : 613843_2
✅ DISCHGON | INCBZD5145E1177 | Request ID : 613843_3

Processing INCBZD5145E1284
✅ CHGON | INCBZD5145E1284 | Request ID : 616447_2
✅ DISCHGON | INCBZD5145E1284 | Request ID : 616447_3

Processing INCBZD5145E1258
✅ CHGON | INCBZD5145E1258 | Request ID : 614193_2
✅ DISCHGON | INCBZD5145E1258 | Request ID : 614193_3

Processing INCBZD5145E1325
✅ CHGON | INCBZD5145E1325 | Request ID : 614691_2
✅ DISCHGON | INCBZD5145E1325 | Request ID : 614691_3

Processing INCBZD5145E1324
✅ CHGON | INCBZD5145E1324 | Request ID : 613593_2
✅ DISCHGON | INCBZD5145E1324 | Request ID : 613593_3

Processing INCBZD5145E1406
✅ CHGON | INCBZD5145E1406 | Request ID : 616366_2
✅ DISCHGON | INCBZD5145E1406 | Request ID : 616366_3

Processing INCBZD5145E1428
✅ CHGON | INCBZD5145E1428 | Request ID : 615936_2
✅ DISCHGON | INCBZD5145E1428 | Request ID : 615936_3

Processing INCBZD5145E1472
✅ CHGON | INCBZD5145E1472 | Request ID : 619600_2
✅ DISCHGON | INCBZD5145E1472 | Request ID : 619600_3

Processing INCBZD5145E1522
✅ CHGON | INCBZD5145E1522 | Request ID : 615972_2
✅ DISCHGON | INCBZD5145E1522 | Request ID : 615972_3

Processing INCBZD5145E1630
✅ CHGON | INCBZD5145E1630 | Request ID : 624226_3
✅ DISCHGON | INCBZD5145E1630 | Request ID : 624226_4

Processing INCBZD5145E1559
✅ CHGON | INCBZD5145E1559 | Request ID : 620791_2
✅ DISCHGON | INCBZD5145E1559 | Request ID : 620791_3

Processing INCBZD5145E1674
✅ CHGON | INCBZD5145E1674 | Request ID : 624207_2
✅ DISCHGON | INCBZD5145E1674 | Request ID : 624207_3

Processing INCBZD5145E1726
✅ CHGON | INCBZD5145E1726 | Request ID : 624448_3
✅ DISCHGON | INCBZD5145E1726 | Request ID : 624448_4

Processing INCBZD5145E1874
✅ CHGON | INCBZD5145E1874 | Request ID : 624393_2
✅ DISCHGON | INCBZD5145E1874 | Request ID : 624393_3

Processing INCBZD5145E2017
✅ CHGON | INCBZD5145E2017 | Request ID : 629397_2
✅ DISCHGON | INCBZD5145E2017 | Request ID : 629397_3

Processing INCBZD5145E2099
✅ CHGON | INCBZD5145E2099 | Request ID : 620765_2
✅ DISCHGON | INCBZD5145E2099 | Request ID : 620765_3

Processing INCBZD5145E2104
✅ CHGON | INCBZD5145E2104 | Request ID : 619185_3
✅ DISCHGON | INCBZD5145E2104 | Request ID : 619185_4

Processing INCBZD5145E2103
✅ CHGON | INCBZD5145E2103 | Request ID : 620598_2
✅ DISCHGON | INCBZD5145E2103 | Request ID : 620598_3

Processing INCBZD5145E2062
✅ CHGON | INCBZD5145E2062 | Request ID : 613692_2
✅ DISCHGON | INCBZD5145E2062 | Request ID : 613692_3

Processing INCBZD5145E2171
✅ CHGON | INCBZD5145E2171 | Request ID : 635648_2
✅ DISCHGON | INCBZD5145E2171 | Request ID : 635648_3

Processing INCBZD5145E2172
✅ CHGON | INCBZD5145E2172 | Request ID : 619421_3
✅ DISCHGON | INCBZD5145E2172 | Request ID : 619421_4

Processing INCBZD5145E2185
✅ CHGON | INCBZD5145E2185 | Request ID : 628124_2
✅ DISCHGON | INCBZD5145E2185 | Request ID : 628124_3

Processing INCBZD5145E2206
✅ CHGON | INCBZD5145E2206 | Request ID : 628174_2
✅ DISCHGON | INCBZD5145E2206 | Request ID : 628174_3

Processing INCBZD5145E2210
✅ CHGON | INCBZD5145E2210 | Request ID : 627324_3
✅ DISCHGON | INCBZD5145E2210 | Request ID : 627324_4

Processing INCBZD5145E2287
✅ CHGON | INCBZD5145E2287 | Request ID : 627025_2
✅ DISCHGON | INCBZD5145E2287 | Request ID : 627025_3

Processing INCBZD5145E2234
✅ CHGON | INCBZD5145E2234 | Request ID : 627225_2
✅ DISCHGON | INCBZD5145E2234 | Request ID : 627225_3

Processing INCBZD5145E2302
✅ CHGON | INCBZD5145E2302 | Request ID : 629301_2
✅ DISCHGON | INCBZD5145E2302 | Request ID : 629301_3

Processing INCBZD5145E2357
✅ CHGON | INCBZD5145E2357 | Request ID : 522717_2
✅ DISCHGON | INCBZD5145E2357 | Request ID : 522717_3

Processing INCBZD5145E2371
✅ CHGON | INCBZD5145E2371 | Request ID : 627565_3
✅ DISCHGON | INCBZD5145E2371 | Request ID : 627565_4

Processing INCBZD5145E2428
✅ CHGON | INCBZD5145E2428 | Request ID : 398997_2
✅ DISCHGON | INCBZD5145E2428 | Request ID : 398997_3

Processing INCBZD5145E2435
✅ CHGON | INCBZD5145E2435 | Request ID : 620204_3
✅ DISCHGON | INCBZD5145E2435 | Request ID : 620204_4

Processing INCBZD5145E2438
✅ CHGON | INCBZD5145E2438 | Request ID : 618574_3
✅ DISCHGON | INCBZD5145E2438 | Request ID : 618574_4

Processing INCBZD5145E2458
✅ CHGON | INCBZD5145E2458 | Request ID : 628003_2
✅ DISCHGON | INCBZD5145E2458 | Request ID : 628003_3

Processing INCBZE5145E0069
✅ CHGON | INCBZE5145E0069 | Request ID : 569292_4
✅ DISCHGON | INCBZE5145E0069 | Request ID : 569292_5

Processing INCBZE5145E0085
✅ CHGON | INCBZE5145E0085 | Request ID : 629023_2
✅ DISCHGON | INCBZE5145E0085 | Request ID : 629023_3

Processing INCBZE5145E0082
✅ CHGON | INCBZE5145E0082 | Request ID : 635180_2
✅ DISCHGON | INCBZE5145E0082 | Request ID : 635180_3

Processing INCBZE5145E0737
✅ CHGON | INCBZE5145E0737 | Request ID : 657097_4
✅ DISCHGON | INCBZE5145E0737 | Request ID : 657097_5

Processing INCBZE5145E0744
✅ CHGON | INCBZE5145E0744 | Request ID : 653488_2
✅ DISCHGON | INCBZE5145E0744 | Request ID : 653488_3

Processing INCBZE5145E0971
✅ CHGON | INCBZE5145E0971 | Request ID : 666919_3
✅ DISCHGON | INCBZE5145E0971 | Request ID : 666919_4

Processing INCBZE5145E1029
✅ CHGON | INCBZE5145E1029 | Request ID : 653529_4
✅ DISCHGON | INCBZE5145E1029 | Request ID : 653529_5

Processing INCBZE5145E1048
✅ CHGON | INCBZE5145E1048 | Request ID : 653503_3
✅ DISCHGON | INCBZE5145E1048 | Request ID : 653503_4

Processing INCBZE5145E1082
✅ CHGON | INCBZE5145E1082 | Request ID : 667068_2
✅ DISCHGON | INCBZE5145E1082 | Request ID : 667068_3

Processing INCBZE5145E1074
✅ CHGON | INCBZE5145E1074 | Request ID : 653468_2
✅ DISCHGON | INCBZE5145E1074 | Request ID : 653468_3

Processing INCBZE5145E1066
✅ CHGON | INCBZE5145E1066 | Request ID : 670087_3
✅ DISCHGON | INCBZE5145E1066 | Request ID : 670087_4

Processing INCBZE5145E1067
✅ CHGON | INCBZE5145E1067 | Request ID : 666649_2
✅ DISCHGON | INCBZE5145E1067 | Request ID : 666649_3

Processing INCBZE5145E1195
✅ CHGON | INCBZE5145E1195 | Request ID : 666559_2
✅ DISCHGON | INCBZE5145E1195 | Request ID : 666559_3

Processing INCBZE5145E1198
✅ CHGON | INCBZE5145E1198 | Request ID : 670010_4
✅ DISCHGON | INCBZE5145E1198 | Request ID : 670010_5

Processing INCBZE5145E1180
✅ CHGON | INCBZE5145E1180 | Request ID : 666656_2
✅ DISCHGON | INCBZE5145E1180 | Request ID : 666656_3

Processing INCBZE5145E1190
✅ CHGON | INCBZE5145E1190 | Request ID : 666878_2
✅ DISCHGON | INCBZE5145E1190 | Request ID : 666878_3

Processing INCBZE5145E1183
✅ CHGON | INCBZE5145E1183 | Request ID : 651617_2
✅ DISCHGON | INCBZE5145E1183 | Request ID : 651617_3

Processing INCBZE5145E1175
✅ CHGON | INCBZE5145E1175 | Request ID : 669948_4
✅ DISCHGON | INCBZE5145E1175 | Request ID : 669948_5

Processing INCBZE5145E1246
✅ CHGON | INCBZE5145E1246 | Request ID : 654080_3
✅ DISCHGON | INCBZE5145E1246 | Request ID : 654080_4

Processing INCBZE5145E1251
✅ CHGON | INCBZE5145E1251 | Request ID : 651637_2
✅ DISCHGON | INCBZE5145E1251 | Request ID : 651637_3

Processing INCBZE5145E1231
✅ CHGON | INCBZE5145E1231 | Request ID : 669986_2
✅ DISCHGON | INCBZE5145E1231 | Request ID : 669986_3

Processing INCBZE5145E1232
✅ CHGON | INCBZE5145E1232 | Request ID : 667011_2
✅ DISCHGON | INCBZE5145E1232 | Request ID : 667011_3

Processing INCBZE5145E1216
✅ CHGON | INCBZE5145E1216 | Request ID : 670083_3
✅ DISCHGON | INCBZE5145E1216 | Request ID : 670083_4

Processing INCBZE5145E1128
✅ CHGON | INCBZE5145E1128 | Request ID : 670185_3
✅ DISCHGON | INCBZE5145E1128 | Request ID : 670185_4

Processing INCBZE5145E1277
✅ CHGON | INCBZE5145E1277 | Request ID : 651523_2
✅ DISCHGON | INCBZE5145E1277 | Request ID : 651523_3

Processing INCBZE5145E1291
✅ CHGON | INCBZE5145E1291 | Request ID : 670043_2
✅ DISCHGON | INCBZE5145E1291 | Request ID : 670043_3

Processing INCBZE5145E1288
✅ CHGON | INCBZE5145E1288 | Request ID : 651534_2
✅ DISCHGON | INCBZE5145E1288 | Request ID : 651534_3

Processing INCBZE5145E1280
✅ CHGON | INCBZE5145E1280 | Request ID : 653522_4
✅ DISCHGON | INCBZE5145E1280 | Request ID : 653522_5

,batteryId,deviceId,manufacturerName,serialNo,action_timestamp,action_date,state,action,CHG CMD,DISCHG CMD,chg_rid,dischg_rid,lat,lon
0,B746083,973019C482B905F2,BATTRIXX,B1_51105_B_120205,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,426922_23,426922_24,None,None
1,B911661,206B78E81B8583B5,INVERTED,INCBZC5145E0075,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,608088_5,608088_6,None,None
2,B912048,DD9C831E66CDB4A7,INVERTED,INCBZD5145E0296,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,614232_3,614232_4,None,None
3,B912820,0633779BFAF5BC64,INVERTED,INCBZD5145E0566,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,635075_3,635075_4,None,None
4,B912825,E86657A9ECE3116E,INVERTED,INCBZD5145E0571,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,614743_2,614743_3,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,B997846,F34BC7BA190F6E48,INVERTED,INCBZE5145E1128,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,670185_3,670185_4,None,None
78,B997863,959A8BEF11DEB324,INVERTED,INCBZE5145E1277,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,651523_2,651523_3,None,None
79,B997872,CE99027B50816BBC,INVERTED,INCBZE5145E1291,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,670043_2,670043_3,None,None
80,B997873,B8C1651F6E0356D9,INVERTED,INCBZE5145E1288,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,651534_2,651534_3,None,None
81,B997877,99A0716344B8589C,INVERTED,INCBZE5145E1280,2026-06-26T17:25:42.833024+05:30,2026-06-26,None,turned_on,CHGON,DISCHGON,653522_4,653522_5,None,None

In [32]:
append(turned_on_df,"https://docs.google.com/spreadsheets/d/12kPyTZb1PILSulIN6uITJwy3uCvg-c8TJtgFd9UEZmw/edit?pli=1&gid=1581823282#gid=1581823282","logs")

append(): wrote df starting at A11782

In [2]:
charging = trinoFetch("""
SELECT
    deviceId,
    startLat,
    startLon,
    startTs,
    endTs
FROM iceberg.silver.charging_discharging_events_new
WHERE deviceId IS NOT NULL
  AND state = 'charging'
  AND startTs >= CURRENT_DATE - INTERVAL '3' DAY
  AND startTs <  CURRENT_DATE
  AND (endSoc - startSoc) > 10
  AND startLat <> 25
  AND startLon <> -71
""")

print(f"  Charging events fetched: {len(charging)}")
print(charging["startTs"].min())
print(charging["startTs"].max())

2026-06-24 18:51:44,442 - INFO - Executing Trino query on iceberg...
2026-06-24 18:52:03,114 - INFO - Trino query executed successfully. Rows fetched: 305499

  Charging events fetched: 305499
2026-06-20 18:30:00+00:00
2026-06-23 18:25:00+00:00

In [3]:
charging_df=charging.copy()

In [4]:

print("\nSTEP 2: Fetching reference locations...")

partners_df = prodFetch('''
SELECT id AS partnerId, zoneId, latitude AS p_lat, longitude AS p_long
FROM partners
WHERE deletedAt IS NULL AND status = 'active' AND deployedBatteries > 0;
''')

warehouses_df = prodFetch('''
SELECT id AS warehouseId,zoneId, latitude AS w_lat, longitude AS w_long
FROM warehouses
WHERE deletedAt IS NULL AND status = 'active';
''')

client_df = prodFetch('''
SELECT id AS clientId,zoneId, latitude AS c_lat, longitude AS c_long
FROM entities
WHERE id LIKE 'CH%' AND status = 'active' AND deletedAt IS NULL
''')


print(f"  Partners: {len(partners_df)} | Warehouses: {len(warehouses_df)} | "
      f"Clients: {len(client_df)}")

STEP 2: Fetching reference locations...

2026-06-24 18:52:03,982 - INFO - Executing query on MySQL DB: batterysmart_prod
2026-06-24 18:52:04,513 - INFO - package: mysql.connector.plugins
2026-06-24 18:52:04,516 - INFO - plugin_name: mysql_native_password
2026-06-24 18:52:04,530 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2026-06-24 18:52:05,440 - INFO - batterysmart_prod → fetched 1314 rows
2026-06-24 18:52:05,446 - INFO - Executing query on MySQL DB: batterysmart_prod
2026-06-24 18:52:06,566 - INFO - batterysmart_prod → fetched 88 rows
2026-06-24 18:52:06,574 - INFO - Executing query on MySQL DB: batterysmart_prod
2026-06-24 18:52:07,673 - INFO - batterysmart_prod → fetched 132 rows

  Partners: 1314 | Warehouses: 88 | Clients: 132

In [5]:
print("\nSTEP 3: Building location BallTree index...")

partners_df["type"] = "partner"
partners_df = partners_df.rename(
    columns={
        "partnerId": "location_id",
        "p_lat": "lat",
        "p_long": "lon"
    }
)

warehouses_df["type"] = "warehouse"
warehouses_df = warehouses_df.rename(
    columns={
        "warehouseId": "location_id",
        "w_lat": "lat",
        "w_long": "lon"
    }
)

client_df["type"] = "client"
client_df = client_df.rename(
    columns={
        "clientId": "location_id",
        "c_lat": "lat",
        "c_long": "lon"
    }
)

# =========================================
# COMBINE ALL LOCATIONS
# =========================================

locations = pd.concat([
    partners_df[[
        "location_id",
        "lat",
        "lon",
        "type",
        "zoneId"
    ]],

    warehouses_df[[
        "location_id",
        "lat",
        "lon",
        "type",
        "zoneId"
    ]],

    client_df[[
        "location_id",
        "lat",
        "lon",
        "type",
        "zoneId"
    ]]

], ignore_index=True)

# =========================================
# RADIAN CONVERSION
# =========================================

locations["lat_rad"] = np.radians(locations["lat"])
locations["lon_rad"] = np.radians(locations["lon"])

charging_df["lat_rad"] = np.radians(charging_df["startLat"])
charging_df["lon_rad"] = np.radians(charging_df["startLon"])

# =========================================
# BALL TREE
# =========================================

tree = BallTree(
    locations[["lat_rad", "lon_rad"]].values,
    metric="haversine"
)

dist, ind = tree.query(
    charging_df[["lat_rad", "lon_rad"]].values,
    k=1
)

# =========================================
# TAGGING
# =========================================

charging_df["distance_m"] = (
    dist.flatten() * 6371000
)

charging_df["nearest_index"] = ind.flatten()

charging_df["location_type"] = charging_df[
    "nearest_index"
].map(
    locations["type"].to_dict()
)

charging_df["nearest_zone"] = charging_df[
    "nearest_index"
].map(
    locations["zoneId"].to_dict()
)

charging_df["charging_location_type"] = np.where(
    charging_df["distance_m"] <= 200,
    charging_df["location_type"],
    "outside"
)

STEP 3: Building location BallTree index...

In [6]:
charging_df=charging_df.drop(columns=["nearest_index"])

In [7]:
charging_df

,deviceId,startLat,startLon,startTs,endTs,lat_rad,lon_rad,distance_m,location_type,nearest_zone,charging_location_type
0,0124AEB6CEB9F554,28.690517,77.268810,2026-06-21 23:00:00+00:00,2026-06-21 23:55:00+00:00,0.500744,1.348595,64.849022,partner,SHG01,partner
1,01A9FBE897D4BE99,23.160597,79.918700,2026-06-21 04:20:00+00:00,2026-06-21 07:25:00+00:00,0.404229,1.394844,518.956737,warehouse,NMP04,outside
2,01CD8C71F23E506E,21.131474,79.126910,2026-06-21 14:30:00+00:00,2026-06-21 16:25:00+00:00,0.368814,1.381025,1684.270383,partner,MHR01,outside
3,022887081077A0C8,27.579994,81.605500,2026-06-21 22:15:00+00:00,2026-06-21 23:55:00+00:00,0.481362,1.424285,13.073620,partner,LKR07,partner
4,02CDEF4A2AFB3DB1,27.495600,77.678360,2026-06-21 11:25:00+00:00,2026-06-21 12:45:00+00:00,0.479889,1.355743,63.513421,partner,MVA01,partner
...,...,...,...,...,...,...,...,...,...,...,...
305494,FBD8221B546B1962,27.499107,77.663410,2026-06-23 12:35:00+00:00,2026-06-23 14:30:00+00:00,0.479950,1.355482,4.542855,partner,MVA01,partner
305495,FD150BD786925EEC,27.563828,80.682140,2026-06-23 10:40:00+00:00,2026-06-23 12:40:00+00:00,0.481080,1.408169,30.251254,partner,LKR06,partner
305496,FD24D8DE05488CF7,26.106682,85.391075,2026-06-23 14:20:00+00:00,2026-06-23 17:05:00+00:00,0.455648,1.490355,54.417817,partner,BHR04,partner
305497,FE0B6357CCB447D1,25.936153,84.192040,2026-06-23 03:10:00+00:00,2026-06-23 04:15:00+00:00,0.452671,1.469428,20839.999845,warehouse,EUP07,outside
305498,FEDC837076C86507,26.736963,83.372510,2026-06-23 07:20:00+00:00,2026-06-23 09:10:00+00:00,0.466648,1.455125,19.317009,partner,EUP04,partner

In [8]:
# %%
# =========================================
# REMOVE REGION ZONES
# EXAMPLE:
# NWD01, NWD02
# LKR01, LKR02
# NMV01
# EUP01
# =========================================

# remove_regions = [
#     "NWD",
#     "NMV",
#     "DNG",  # DNG01, DNG02
#     "SHG",  # SHG03
#     "MVA",  # MVA01
#     "FSD",  # FSD01
# ]

removed_zones= ["NMP03","JHR01","JHR02","KOL01"]

charging_df = charging_df[
    ~charging_df["nearest_zone"]
    .isin(removed_zones)
].copy()

# print(
#     f"Remaining rows after region removal : "
#     f"{len(charging_df)}"
# )

In [9]:
device_summary = charging_df.groupby("deviceId").agg(
    total_events=("deviceId", "count"),
    valid_events=("charging_location_type",
                  lambda x: x.isin(["partner", "warehouse", "client"]).sum())
).reset_index()

filtered_devices = device_summary[device_summary["total_events"] >= 1]
always_outside   = filtered_devices[filtered_devices["valid_events"] == 0]

print(f"  Always-outside devices: {len(always_outside)} | With >1 events: {len(filtered_devices)}")

  Always-outside devices: 23924 | With >1 events: 117410

In [10]:
always_outside

                     deviceId  total_events  valid_events
1       000005861919085382801             2             0
2       000005861919085382827             3             0
3       000005861919085382868             2             0
4       000005861919085384559             3             0
5       000005861919085384617             1             0
...                       ...           ...           ...
117377       FEEBF1BB0C083329             8             0
117384       FEEF5575A0A32F30             2             0
117391       FEF629CBAB4617D8             2             0
117395       FEF7625C69E405D2             1             0
117404       FEFC33D09FEA0CE0             3             0

[23924 rows x 3 columns]

In [11]:
always_outside['deviceId']=always_outside['deviceId'].astype(str)

In [12]:
# %%
print("\nSTEP 5: Mapping devices to batteries...")

batteries_df = prodFetch("""
SELECT 
    id AS batteryId,
    serialNo,
    manufacturerName,
    iotDeviceNo as deviceId,batteryType,phase
FROM batteries
WHERE deletedAt IS NULL
  AND isBaas = 0;
""")

batteries_df['deviceId']=batteries_df['deviceId'].astype(str)
batteries_df['batteryId']=batteries_df['batteryId'].astype(str)
batteries_df['serialNo']=batteries_df['serialNo'].astype(str)

final_battery_map = pd.merge(
    always_outside, batteries_df,
    on="deviceId",
    how="left"
)

2026-06-24 18:52:55,621 - INFO - Executing query on MySQL DB: batterysmart_prod

STEP 5: Mapping devices to batteries...

2026-06-24 18:53:09,406 - INFO - batterysmart_prod → fetched 292105 rows

In [13]:
final_battery_map=final_battery_map[final_battery_map['batteryId'].isna()==False]
final_battery_map

,deviceId,total_events,valid_events,batteryId,serialNo,manufacturerName,batteryType,phase
66,011BB223A7E28202,2,0,B932911,B112004450_125992,BATTRIXX,LFP,2.0
93,016ABA8BC4596FAB,1,0,B290911,A24-30788,STEFEN ELECTRIC,NMC,2.0
115,01A27AF67C357DAD,2,0,B988626,L22-00466,STEFEN ELECTRIC,NMC,1.0
134,01D6E5248519D915,1,0,B957604,A24-32167,STEFEN ELECTRIC,NMC,2.0
136,01DDAF8831129A77,3,0,B481807,H24-52998,STEFEN ELECTRIC,NMC,2.0
...,...,...,...,...,...,...,...,...
23842,FDF150BC164191D5,2,0,B856124,B112004450_123917,BATTRIXX,LFP,2.0
23843,FDF791D41DE9BCC8,2,0,B858615,B112004450_124425,BATTRIXX,LFP,2.0
23852,FE1D4B60492570EA,4,0,B340023,MD0AI2LKAA00033,LIVGUARD,NMC,1.0
23889,FE81F968F4696636,1,0,B933011,B112004450_125979,BATTRIXX,LFP,2.0
23897,FEA6A38EDB73C8D7,1,0,B818367,B112004450_123235,BATTRIXX,LFP,2.0

In [14]:
valid_serialNo = final_battery_map[
    final_battery_map["serialNo"].notna()
]["serialNo"].unique().tolist()

serialNo_set = set(valid_serialNo)
print(f"  Mapped batteries: {len(serialNo_set)}")

  Mapped batteries: 1830

In [15]:
print("\nSTEP 6: FETCHING LAST 3 DAY TRANSACTIONS...\n")

valid_ids_sql = ",".join(
    [f"'{x}'" for x in valid_serialNo]
)

STEP 6: FETCHING LAST 3 DAY TRANSACTIONS...

## change this to transactions

In [16]:
batteries = prodFetch(f""" select id as batteryId, serialNo, iotDeviceNo from batteries b where isBaas=0 """)


txnLogs = prodFetch(f"""
select t.partnerId,t.driverId, t.batteriesIssued, t.batteriesReceived,t.createdAt, t.updatedAt,
t.status,t.id as txnId from transactions t
where createdAt >= CURRENT_DATE() - interval 3 day
and t.deletedAt is  null """)

txnLogs['createdAt'] = txnLogs['createdAt']+pd.Timedelta(minutes=330)
txnLogs['updatedAt'] = txnLogs['updatedAt']+pd.Timedelta(minutes=330)


txnLogs['date'] = txnLogs['createdAt'].dt.date

import ast
txnLogs['batteriesReceived'] = txnLogs['batteriesReceived'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])
txnLogs['batteriesIssued'] = txnLogs['batteriesIssued'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])

txnLogs['batteryRc1'] = txnLogs['batteriesReceived'].apply(lambda x: x[0] if len(x) > 0 else None)
txnLogs['batteryRc2'] = txnLogs['batteriesReceived'].apply(lambda x: x[1] if len(x) > 1 else None)
txnLogs['batteryIs1'] = txnLogs['batteriesIssued'].apply(lambda x: x[0] if len(x) > 0 else None)
txnLogs['batteryIs2'] = txnLogs['batteriesIssued'].apply(lambda x: x[1] if len(x) > 1 else None)


txnLogs = txnLogs.melt(
    id_vars=['partnerId', 'driverId', 'createdAt','updatedAt','date'],
    value_vars=['batteryRc1', 'batteryRc2', 'batteryIs1', 'batteryIs2'],
    var_name='batteryType',
    value_name='batteryId'
)

2026-06-24 18:53:10,193 - INFO - Executing query on MySQL DB: batterysmart_prod
2026-06-24 18:53:35,592 - INFO - batterysmart_prod → fetched 729692 rows
2026-06-24 18:53:35,659 - INFO - Executing query on MySQL DB: batterysmart_prod
2026-06-24 18:53:50,472 - INFO - batterysmart_prod → fetched 234356 rows

In [17]:
txnLogs2 = txnLogs.merge(batteries,on='batteryId',how='left')
txnLogs2.sort_values(by='createdAt',inplace=True)
txnLogs2=txnLogs2[txnLogs2['serialNo'].isna()==False]
txnLogs2

,partnerId,driverId,createdAt,updatedAt,date,batteryType,batteryId,serialNo,iotDeviceNo
0,P1883,D114549,2026-06-21 05:30:05,2026-06-21 05:30:40,2026-06-21,batteryRc1,B1002135,B112004450_127648,7EBACF588DABF8C6
468712,P1883,D114549,2026-06-21 05:30:05,2026-06-21 05:30:40,2026-06-21,batteryIs1,B997419,INCBZE5145E1005,8507E6293EF41645
1,P5030,D121270,2026-06-21 05:30:31,2026-06-21 05:32:12,2026-06-21,batteryRc1,B639881,TK-5145-25AY-C-020448,1D4D098C0A016638
234357,P5030,D121270,2026-06-21 05:30:31,2026-06-21 05:32:12,2026-06-21,batteryRc2,B748227,TK-5145-10GY-C-029295,2A28205B77803964
703069,P5030,D121270,2026-06-21 05:30:31,2026-06-21 05:32:12,2026-06-21,batteryIs2,B818240,B112004450_122951,440BFDFD11912CA3
...,...,...,...,...,...,...,...,...,...
468709,P4947,D31459,2026-06-24 18:52:49,2026-06-24 18:53:23,2026-06-24,batteryRc2,B506532,INDMXL5140E0528,A13C8C464192F122
703066,P4034,D91172,2026-06-24 18:52:56,2026-06-24 18:53:29,2026-06-24,batteryIs1,B682797,INDMXC516200015,465D44D146A9039D
234354,P4034,D91172,2026-06-24 18:52:56,2026-06-24 18:53:29,2026-06-24,batteryRc1,B417450,INDMXD516200046,ECB18BA759B3A1C8
234355,P5549,D148506,2026-06-24 18:52:59,2026-06-24 18:53:34,2026-06-24,batteryRc1,B995649,INCBZE5145E0116,CA7FF5DCC34864E4
703067,P5549,D148506,2026-06-24 18:52:59,2026-06-24 18:53:34,2026-06-24,batteryIs1,B913950,INCBZD5145E1453,E7970C6C31DAFC2C

In [18]:
txn_df=txnLogs2.copy()

In [19]:
final_battery_map=final_battery_map[~final_battery_map['serialNo'].isin(txn_df['serialNo'])]
final_battery_map

,deviceId,total_events,valid_events,batteryId,serialNo,manufacturerName,batteryType,phase
66,011BB223A7E28202,2,0,B932911,B112004450_125992,BATTRIXX,LFP,2.0
93,016ABA8BC4596FAB,1,0,B290911,A24-30788,STEFEN ELECTRIC,NMC,2.0
115,01A27AF67C357DAD,2,0,B988626,L22-00466,STEFEN ELECTRIC,NMC,1.0
134,01D6E5248519D915,1,0,B957604,A24-32167,STEFEN ELECTRIC,NMC,2.0
148,01F4BA65BA0B486A,2,0,B509265,B112003240_121904,BATTRIXX,LFP,2.0
...,...,...,...,...,...,...,...,...
23780,FD46C1CC0EDE7452,1,0,B932857,B112004450_126053,BATTRIXX,LFP,2.0
23842,FDF150BC164191D5,2,0,B856124,B112004450_123917,BATTRIXX,LFP,2.0
23843,FDF791D41DE9BCC8,2,0,B858615,B112004450_124425,BATTRIXX,LFP,2.0
23852,FE1D4B60492570EA,4,0,B340023,MD0AI2LKAA00033,LIVGUARD,NMC,1.0
23889,FE81F968F4696636,1,0,B933011,B112004450_125979,BATTRIXX,LFP,2.0

In [20]:
final_battery_map=final_battery_map.drop_duplicates(subset=['batteryId'], keep='first')
final_battery_map

,deviceId,total_events,valid_events,batteryId,serialNo,manufacturerName,batteryType,phase
66,011BB223A7E28202,2,0,B932911,B112004450_125992,BATTRIXX,LFP,2.0
93,016ABA8BC4596FAB,1,0,B290911,A24-30788,STEFEN ELECTRIC,NMC,2.0
115,01A27AF67C357DAD,2,0,B988626,L22-00466,STEFEN ELECTRIC,NMC,1.0
134,01D6E5248519D915,1,0,B957604,A24-32167,STEFEN ELECTRIC,NMC,2.0
148,01F4BA65BA0B486A,2,0,B509265,B112003240_121904,BATTRIXX,LFP,2.0
...,...,...,...,...,...,...,...,...
23780,FD46C1CC0EDE7452,1,0,B932857,B112004450_126053,BATTRIXX,LFP,2.0
23842,FDF150BC164191D5,2,0,B856124,B112004450_123917,BATTRIXX,LFP,2.0
23843,FDF791D41DE9BCC8,2,0,B858615,B112004450_124425,BATTRIXX,LFP,2.0
23852,FE1D4B60492570EA,4,0,B340023,MD0AI2LKAA00033,LIVGUARD,NMC,1.0
23889,FE81F968F4696636,1,0,B933011,B112004450_125979,BATTRIXX,LFP,2.0

In [21]:
# final_battery_map=final_battery_map[~((final_battery_map['batteryType']=='NMC') & (final_battery_map['manufacturerName']=='LIVGUARD'))]
# final_battery_map.shape

## latest UC location

In [22]:
# =========================================
# ADD LATEST UNAUTHORIZED CHARGING LAT/LON
# =========================================

latest_charging_location = (
    charging_df[charging_df["deviceId"].isin(final_battery_map["deviceId"])]
    .sort_values("startTs")
    .groupby("deviceId", as_index=False)
    .last()[["deviceId", "startLat", "startLon", "startTs"]]
    .rename(columns={"startLat": "lat", "startLon": "lon", "startTs": "latest_unauth_charging_ts"})
)

final_battery_map = final_battery_map.merge(
    latest_charging_location,
    on="deviceId",
    how="left"
)

print(f"  Lat/Lon mapped for: {final_battery_map['lat'].notna().sum()} / {len(final_battery_map)} devices")

  Lat/Lon mapped for: 1325 / 1325 devices

In [23]:
final_battery_map

,deviceId,total_events,valid_events,batteryId,serialNo,manufacturerName,batteryType,phase,lat,lon,latest_unauth_charging_ts
0,011BB223A7E28202,2,0,B932911,B112004450_125992,BATTRIXX,LFP,2.0,28.492338,77.058180,2026-06-22 15:55:00+00:00
1,016ABA8BC4596FAB,1,0,B290911,A24-30788,STEFEN ELECTRIC,NMC,2.0,28.525982,77.531296,2026-06-21 06:45:00+00:00
2,01A27AF67C357DAD,2,0,B988626,L22-00466,STEFEN ELECTRIC,NMC,1.0,28.663242,77.181080,2026-06-23 09:20:00+00:00
3,01D6E5248519D915,1,0,B957604,A24-32167,STEFEN ELECTRIC,NMC,2.0,28.613644,77.346740,2026-06-23 12:25:00+00:00
4,01F4BA65BA0B486A,2,0,B509265,B112003240_121904,BATTRIXX,LFP,2.0,26.804523,75.831220,2026-06-22 21:50:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...
1320,FD46C1CC0EDE7452,1,0,B932857,B112004450_126053,BATTRIXX,LFP,2.0,28.438530,77.049126,2026-06-21 11:15:00+00:00
1321,FDF150BC164191D5,2,0,B856124,B112004450_123917,BATTRIXX,LFP,2.0,27.104733,78.006410,2026-06-22 20:40:00+00:00
1322,FDF791D41DE9BCC8,2,0,B858615,B112004450_124425,BATTRIXX,LFP,2.0,27.486288,77.669150,2026-06-21 22:35:00+00:00
1323,FE1D4B60492570EA,4,0,B340023,MD0AI2LKAA00033,LIVGUARD,NMC,1.0,28.656187,77.216220,2026-06-23 00:15:00+00:00
1324,FE81F968F4696636,1,0,B933011,B112004450_125979,BATTRIXX,LFP,2.0,26.154726,80.495350,2026-06-23 13:00:00+00:00

In [24]:
write(final_battery_map,"https://docs.google.com/spreadsheets/d/12kPyTZb1PILSulIN6uITJwy3uCvg-c8TJtgFd9UEZmw/edit?gid=0#gid=0","Today_filtered_batteries")

2026-06-24 18:54:08,389 - INFO - Pygsheets client authorized successfully.

written successfully